# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import controller_pb2 as controller__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerServiceStub(object):
    """API for controllers to receive work from the engine.

    The engine matches ConfigurationComponent entities to DeviceComponent entities
    using the config's selector, and streams the results as
    ControllerDeviceConfigurationEvent messages carrying both the config and device entity.

    ## Engine guarantees

    - Every New event is eventually followed by a Removed event
    for that (config.id, device.id) pair.
    - Each event carries the full config and device entities.

    ## Event sequences by scenario

    Stream starts:
    New(config, device) for each existing match

    Config added, no devices match yet:
    (no events until a device matches)

    Config added, devices already match:
    New(config, device) for each match

    Config value updated (selector unchanged):
    Changed(config, device) for all matched devices
    (carries new config entity)

    Config selector changed:
    Removed(config, device) for devices that no longer match
    New(config, device) for newly matching devices
    Changed(config, device) for devices that still match

    Config removed:
    Removed(config, device) for all matched devices

    Device appears, matches existing config(s):
    New(config, device) per matching config

    Device updated, still matches:
    Changed(config, device) with updated device entity

    Device updated, match set changes:
    Removed(config, device) from configs it no longer matches
    New(config, device) to configs it now newly matches

    Device removed:
    Removed(config, device) for each config it was matched to

    ## 1:1 mode — one connector per (config, device) pair

    New     → start connector (carries full config + device)
    Changed → restart connector, or pass update to running connector
    Removed → stop connector

    ## 1:N mode — one connector per config, devices added/removed dynamically

    New     → add device to connector, start connector if first device for this config
    Changed → update device or config in connector
    Removed → remove device from connector, stop connector if last device removed

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reconcile = channel.unary_stream(
                '/world.ControllerService/Reconcile',
                request_serializer=controller__pb2.ControllerReconciliationRequest.SerializeToString,
                response_deserializer=controller__pb2.ControllerReconciliationEvent.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """API for controllers to receive work from the engine.

    The engine matches ConfigurationComponent entities to DeviceComponent entities
    using the config's selector, and streams the results as
    ControllerDeviceConfigurationEvent messages carrying both the config and device entity.

    ## Engine guarantees

    - Every New event is eventually followed by a Removed event
    for that (config.id, device.id) pair.
    - Each event carries the full config and device entities.

    ## Event sequences by scenario

    Stream starts:
    New(config, device) for each existing match

    Config added, no devices match yet:
    (no events until a device matches)

    Config added, devices already match:
    New(config, device) for each match

    Config value updated (selector unchanged):
    Changed(config, device) for all matched devices
    (carries new config entity)

    Config selector changed:
    Removed(config, device) for devices that no longer match
    New(config, device) for newly matching devices
    Changed(config, device) for devices that still match

    Config removed:
    Removed(config, device) for all matched devices

    Device appears, matches existing config(s):
    New(config, device) per matching config

    Device updated, still matches:
    Changed(config, device) with updated device entity

    Device updated, match set changes:
    Removed(config, device) from configs it no longer matches
    New(config, device) to configs it now newly matches

    Device removed:
    Removed(config, device) for each config it was matched to

    ## 1:1 mode — one connector per (config, device) pair

    New     → start connector (carries full config + device)
    Changed → restart connector, or pass update to running connector
    Removed → stop connector

    ## 1:N mode — one connector per config, devices added/removed dynamically

    New     → add device to connector, start connector if first device for this config
    Changed → update device or config in connector
    Removed → remove device from connector, stop connector if last device removed

    """

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reconcile': grpc.unary_stream_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=controller__pb2.ControllerReconciliationRequest.FromString,
                    response_serializer=controller__pb2.ControllerReconciliationEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """API for controllers to receive work from the engine.

    The engine matches ConfigurationComponent entities to DeviceComponent entities
    using the config's selector, and streams the results as
    ControllerDeviceConfigurationEvent messages carrying both the config and device entity.

    ## Engine guarantees

    - Every New event is eventually followed by a Removed event
    for that (config.id, device.id) pair.
    - Each event carries the full config and device entities.

    ## Event sequences by scenario

    Stream starts:
    New(config, device) for each existing match

    Config added, no devices match yet:
    (no events until a device matches)

    Config added, devices already match:
    New(config, device) for each match

    Config value updated (selector unchanged):
    Changed(config, device) for all matched devices
    (carries new config entity)

    Config selector changed:
    Removed(config, device) for devices that no longer match
    New(config, device) for newly matching devices
    Changed(config, device) for devices that still match

    Config removed:
    Removed(config, device) for all matched devices

    Device appears, matches existing config(s):
    New(config, device) per matching config

    Device updated, still matches:
    Changed(config, device) with updated device entity

    Device updated, match set changes:
    Removed(config, device) from configs it no longer matches
    New(config, device) to configs it now newly matches

    Device removed:
    Removed(config, device) for each config it was matched to

    ## 1:1 mode — one connector per (config, device) pair

    New     → start connector (carries full config + device)
    Changed → restart connector, or pass update to running connector
    Removed → stop connector

    ## 1:N mode — one connector per config, devices added/removed dynamically

    New     → add device to connector, start connector if first device for this config
    Changed → update device or config in connector
    Removed → remove device from connector, stop connector if last device removed

    """

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.ControllerService/Reconcile',
            controller__pb2.ControllerReconciliationRequest.SerializeToString,
            controller__pb2.ControllerReconciliationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
