# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import world_pb2 as world__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\x05world\x1a\x0bworld.proto\"5\n\x1f\x43ontrollerReconciliationRequest\x12\x12\n\ncontroller\x18\x01 \x01(\t\"\x9c\x01\n\"ControllerDeviceConfigurationEvent\x12\x38\n\x01t\x18\x01 \x01(\x0e\x32-.world.ControllerDeviceConfigurationEventType\x12\x1d\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\r.world.Entity\x12\x1d\n\x06\x64\x65vice\x18\x03 \x01(\x0b\x32\r.world.Entity\"e\n\x1d\x43ontrollerReconciliationEvent\x12;\n\x06\x63onfig\x18\x02 \x01(\x0b\x32).world.ControllerDeviceConfigurationEventH\x00\x42\x07\n\x05\x65vent*\xb1\x01\n&ControllerDeviceConfigurationEventType\x12)\n%ControllerDeviceConfigurationEventNew\x10\x00\x12-\n)ControllerDeviceConfigurationEventChanged\x10\x01\x12-\n)ControllerDeviceConfigurationEventRemoved\x10\x02\x32p\n\x11\x43ontrollerService\x12[\n\tReconcile\x12&.world.ControllerReconciliationRequest\x1a$.world.ControllerReconciliationEvent0\x01\x42 Z\x1egithub.com/projectqai/proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/projectqai/proto/go'
  _globals['_CONTROLLERDEVICECONFIGURATIONEVENTTYPE']._serialized_start=358
  _globals['_CONTROLLERDEVICECONFIGURATIONEVENTTYPE']._serialized_end=535
  _globals['_CONTROLLERRECONCILIATIONREQUEST']._serialized_start=40
  _globals['_CONTROLLERRECONCILIATIONREQUEST']._serialized_end=93
  _globals['_CONTROLLERDEVICECONFIGURATIONEVENT']._serialized_start=96
  _globals['_CONTROLLERDEVICECONFIGURATIONEVENT']._serialized_end=252
  _globals['_CONTROLLERRECONCILIATIONEVENT']._serialized_start=254
  _globals['_CONTROLLERRECONCILIATIONEVENT']._serialized_end=355
  _globals['_CONTROLLERSERVICE']._serialized_start=537
  _globals['_CONTROLLERSERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
