# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpolicy.proto\x12\x05world\"i\n\nPolicyRule\x12#\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x13.world.PolicyAction\x12\x10\n\x03\x63\x65l\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05label\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_celB\x08\n\x06_label\"3\n\x0fPolicyComponent\x12 \n\x05rules\x18\x01 \x03(\x0b\x32\x11.world.PolicyRule\"\x10\n\x0e\x45ntitlementCop\"\x15\n\x13\x45ntitlementCopWrite\"\x10\n\x0e\x45ntitlementIam\"\x13\n\x11\x45ntitlementPolicy\"\x14\n\x12\x45ntitlementTasking\"\x1a\n\x18\x45ntitlementConsequential\"\x12\n\x10\x45ntitlementReset\"\x1a\n\x18\x45ntitlementArtifactsRead\"\x14\n\x12\x45ntitlementSecrets\"\x18\n\x16\x45ntitlementSecretsRead\"\xf0\x03\n\x0b\x45ntitlement\x12$\n\x03\x63op\x18\x01 \x01(\x0b\x32\x15.world.EntitlementCopH\x00\x12/\n\tcop_write\x18\x02 \x01(\x0b\x32\x1a.world.EntitlementCopWriteH\x00\x12$\n\x03iam\x18\x03 \x01(\x0b\x32\x15.world.EntitlementIamH\x00\x12*\n\x06policy\x18\x04 \x01(\x0b\x32\x18.world.EntitlementPolicyH\x00\x12,\n\x07tasking\x18\x05 \x01(\x0b\x32\x19.world.EntitlementTaskingH\x00\x12\x38\n\rconsequential\x18\x06 \x01(\x0b\x32\x1f.world.EntitlementConsequentialH\x00\x12(\n\x05reset\x18\x07 \x01(\x0b\x32\x17.world.EntitlementResetH\x00\x12\x39\n\x0e\x61rtifacts_read\x18\x08 \x01(\x0b\x32\x1f.world.EntitlementArtifactsReadH\x00\x12,\n\x07secrets\x18\t \x01(\x0b\x32\x19.world.EntitlementSecretsH\x00\x12\x35\n\x0csecrets_read\x18\n \x01(\x0b\x32\x1d.world.EntitlementSecretsReadH\x00\x42\x06\n\x04kind\"B\n\x16\x41uthorizationComponent\x12(\n\x0c\x65ntitlements\x18\x02 \x03(\x0b\x32\x12.world.Entitlement*\x80\x01\n\x0cPolicyAction\x12\x17\n\x13PolicyActionInvalid\x10\x00\x12\x14\n\x10PolicyActionDeny\x10\x01\x12\x15\n\x11PolicyActionAllow\x10\x02\x12\x13\n\x0fPolicyActionLog\x10\x03\x12\x15\n\x11PolicyActionDefer\x10\x04\x42 Z\x1egithub.com/projectqai/proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/projectqai/proto/go'
  _globals['_POLICYACTION']._serialized_start=977
  _globals['_POLICYACTION']._serialized_end=1105
  _globals['_POLICYRULE']._serialized_start=23
  _globals['_POLICYRULE']._serialized_end=128
  _globals['_POLICYCOMPONENT']._serialized_start=130
  _globals['_POLICYCOMPONENT']._serialized_end=181
  _globals['_ENTITLEMENTCOP']._serialized_start=183
  _globals['_ENTITLEMENTCOP']._serialized_end=199
  _globals['_ENTITLEMENTCOPWRITE']._serialized_start=201
  _globals['_ENTITLEMENTCOPWRITE']._serialized_end=222
  _globals['_ENTITLEMENTIAM']._serialized_start=224
  _globals['_ENTITLEMENTIAM']._serialized_end=240
  _globals['_ENTITLEMENTPOLICY']._serialized_start=242
  _globals['_ENTITLEMENTPOLICY']._serialized_end=261
  _globals['_ENTITLEMENTTASKING']._serialized_start=263
  _globals['_ENTITLEMENTTASKING']._serialized_end=283
  _globals['_ENTITLEMENTCONSEQUENTIAL']._serialized_start=285
  _globals['_ENTITLEMENTCONSEQUENTIAL']._serialized_end=311
  _globals['_ENTITLEMENTRESET']._serialized_start=313
  _globals['_ENTITLEMENTRESET']._serialized_end=331
  _globals['_ENTITLEMENTARTIFACTSREAD']._serialized_start=333
  _globals['_ENTITLEMENTARTIFACTSREAD']._serialized_end=359
  _globals['_ENTITLEMENTSECRETS']._serialized_start=361
  _globals['_ENTITLEMENTSECRETS']._serialized_end=381
  _globals['_ENTITLEMENTSECRETSREAD']._serialized_start=383
  _globals['_ENTITLEMENTSECRETSREAD']._serialized_end=407
  _globals['_ENTITLEMENT']._serialized_start=410
  _globals['_ENTITLEMENT']._serialized_end=906
  _globals['_AUTHORIZATIONCOMPONENT']._serialized_start=908
  _globals['_AUTHORIZATIONCOMPONENT']._serialized_end=974
# @@protoc_insertion_point(module_scope)
