# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timeline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'timeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etimeline.proto\x12\x08timeline\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n\x12GetTimelineRequest\"\x9f\x01\n\x13GetTimelineResponse\x12\'\n\x03min\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03max\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x66rozen\x18\x03 \x01(\x08\x12&\n\x02\x61t\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"M\n\x13MoveTimelineRequest\x12\x0e\n\x06\x66reeze\x18\x01 \x01(\x08\x12&\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"C\n\x14MoveTimelineResponse\x12+\n\x07\x63urrent\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xae\x01\n\x0fTimelineService\x12M\n\x0cMoveTimeline\x12\x1d.timeline.MoveTimelineRequest\x1a\x1e.timeline.MoveTimelineResponse\x12L\n\x0bGetTimeline\x12\x1c.timeline.GetTimelineRequest\x1a\x1d.timeline.GetTimelineResponse0\x01\x42 Z\x1egithub.com/projectqai/proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/projectqai/proto/go'
  _globals['_GETTIMELINEREQUEST']._serialized_start=61
  _globals['_GETTIMELINEREQUEST']._serialized_end=81
  _globals['_GETTIMELINERESPONSE']._serialized_start=84
  _globals['_GETTIMELINERESPONSE']._serialized_end=243
  _globals['_MOVETIMELINEREQUEST']._serialized_start=245
  _globals['_MOVETIMELINEREQUEST']._serialized_end=322
  _globals['_MOVETIMELINERESPONSE']._serialized_start=324
  _globals['_MOVETIMELINERESPONSE']._serialized_end=391
  _globals['_TIMELINESERVICE']._serialized_start=394
  _globals['_TIMELINESERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
