// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: artifacts.proto

package _goconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/projectqai/proto/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtifactServiceName is the fully-qualified name of the ArtifactService service.
	ArtifactServiceName = "world.ArtifactService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtifactServiceDownloadArtifactProcedure is the fully-qualified name of the ArtifactService's
	// DownloadArtifact RPC.
	ArtifactServiceDownloadArtifactProcedure = "/world.ArtifactService/DownloadArtifact"
	// ArtifactServiceUploadArtifactProcedure is the fully-qualified name of the ArtifactService's
	// UploadArtifact RPC.
	ArtifactServiceUploadArtifactProcedure = "/world.ArtifactService/UploadArtifact"
)

// ArtifactServiceClient is a client for the world.ArtifactService service.
type ArtifactServiceClient interface {
	// stream artifact data
	DownloadArtifact(context.Context, *connect.Request[_go.DownloadArtifactRequest]) (*connect.ServerStreamForClient[_go.DownloadArtifactResponse], error)
	// upload or ingest an artifact
	UploadArtifact(context.Context) *connect.ClientStreamForClient[_go.UploadArtifactRequest, _go.UploadArtifactResponse]
}

// NewArtifactServiceClient constructs a client for the world.ArtifactService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactServiceMethods := _go.File_artifacts_proto.Services().ByName("ArtifactService").Methods()
	return &artifactServiceClient{
		downloadArtifact: connect.NewClient[_go.DownloadArtifactRequest, _go.DownloadArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceDownloadArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("DownloadArtifact")),
			connect.WithClientOptions(opts...),
		),
		uploadArtifact: connect.NewClient[_go.UploadArtifactRequest, _go.UploadArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceUploadArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("UploadArtifact")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactServiceClient implements ArtifactServiceClient.
type artifactServiceClient struct {
	downloadArtifact *connect.Client[_go.DownloadArtifactRequest, _go.DownloadArtifactResponse]
	uploadArtifact   *connect.Client[_go.UploadArtifactRequest, _go.UploadArtifactResponse]
}

// DownloadArtifact calls world.ArtifactService.DownloadArtifact.
func (c *artifactServiceClient) DownloadArtifact(ctx context.Context, req *connect.Request[_go.DownloadArtifactRequest]) (*connect.ServerStreamForClient[_go.DownloadArtifactResponse], error) {
	return c.downloadArtifact.CallServerStream(ctx, req)
}

// UploadArtifact calls world.ArtifactService.UploadArtifact.
func (c *artifactServiceClient) UploadArtifact(ctx context.Context) *connect.ClientStreamForClient[_go.UploadArtifactRequest, _go.UploadArtifactResponse] {
	return c.uploadArtifact.CallClientStream(ctx)
}

// ArtifactServiceHandler is an implementation of the world.ArtifactService service.
type ArtifactServiceHandler interface {
	// stream artifact data
	DownloadArtifact(context.Context, *connect.Request[_go.DownloadArtifactRequest], *connect.ServerStream[_go.DownloadArtifactResponse]) error
	// upload or ingest an artifact
	UploadArtifact(context.Context, *connect.ClientStream[_go.UploadArtifactRequest]) (*connect.Response[_go.UploadArtifactResponse], error)
}

// NewArtifactServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactServiceHandler(svc ArtifactServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactServiceMethods := _go.File_artifacts_proto.Services().ByName("ArtifactService").Methods()
	artifactServiceDownloadArtifactHandler := connect.NewServerStreamHandler(
		ArtifactServiceDownloadArtifactProcedure,
		svc.DownloadArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("DownloadArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceUploadArtifactHandler := connect.NewClientStreamHandler(
		ArtifactServiceUploadArtifactProcedure,
		svc.UploadArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("UploadArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	return "/world.ArtifactService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactServiceDownloadArtifactProcedure:
			artifactServiceDownloadArtifactHandler.ServeHTTP(w, r)
		case ArtifactServiceUploadArtifactProcedure:
			artifactServiceUploadArtifactHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactServiceHandler struct{}

func (UnimplementedArtifactServiceHandler) DownloadArtifact(context.Context, *connect.Request[_go.DownloadArtifactRequest], *connect.ServerStream[_go.DownloadArtifactResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("world.ArtifactService.DownloadArtifact is not implemented"))
}

func (UnimplementedArtifactServiceHandler) UploadArtifact(context.Context, *connect.ClientStream[_go.UploadArtifactRequest]) (*connect.Response[_go.UploadArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.ArtifactService.UploadArtifact is not implemented"))
}
