// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: controller.proto

package _goconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/projectqai/proto/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControllerServiceName is the fully-qualified name of the ControllerService service.
	ControllerServiceName = "world.ControllerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControllerServiceReconcileProcedure is the fully-qualified name of the ControllerService's
	// Reconcile RPC.
	ControllerServiceReconcileProcedure = "/world.ControllerService/Reconcile"
)

// ControllerServiceClient is a client for the world.ControllerService service.
type ControllerServiceClient interface {
	Reconcile(context.Context, *connect.Request[_go.ControllerReconciliationRequest]) (*connect.ServerStreamForClient[_go.ControllerReconciliationEvent], error)
}

// NewControllerServiceClient constructs a client for the world.ControllerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControllerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControllerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controllerServiceMethods := _go.File_controller_proto.Services().ByName("ControllerService").Methods()
	return &controllerServiceClient{
		reconcile: connect.NewClient[_go.ControllerReconciliationRequest, _go.ControllerReconciliationEvent](
			httpClient,
			baseURL+ControllerServiceReconcileProcedure,
			connect.WithSchema(controllerServiceMethods.ByName("Reconcile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controllerServiceClient implements ControllerServiceClient.
type controllerServiceClient struct {
	reconcile *connect.Client[_go.ControllerReconciliationRequest, _go.ControllerReconciliationEvent]
}

// Reconcile calls world.ControllerService.Reconcile.
func (c *controllerServiceClient) Reconcile(ctx context.Context, req *connect.Request[_go.ControllerReconciliationRequest]) (*connect.ServerStreamForClient[_go.ControllerReconciliationEvent], error) {
	return c.reconcile.CallServerStream(ctx, req)
}

// ControllerServiceHandler is an implementation of the world.ControllerService service.
type ControllerServiceHandler interface {
	Reconcile(context.Context, *connect.Request[_go.ControllerReconciliationRequest], *connect.ServerStream[_go.ControllerReconciliationEvent]) error
}

// NewControllerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControllerServiceHandler(svc ControllerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controllerServiceMethods := _go.File_controller_proto.Services().ByName("ControllerService").Methods()
	controllerServiceReconcileHandler := connect.NewServerStreamHandler(
		ControllerServiceReconcileProcedure,
		svc.Reconcile,
		connect.WithSchema(controllerServiceMethods.ByName("Reconcile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/world.ControllerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControllerServiceReconcileProcedure:
			controllerServiceReconcileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControllerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControllerServiceHandler struct{}

func (UnimplementedControllerServiceHandler) Reconcile(context.Context, *connect.Request[_go.ControllerReconciliationRequest], *connect.ServerStream[_go.ControllerReconciliationEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("world.ControllerService.Reconcile is not implemented"))
}
