// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: timeline.proto

package _goconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/projectqai/proto/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TimelineServiceName is the fully-qualified name of the TimelineService service.
	TimelineServiceName = "timeline.TimelineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TimelineServiceMoveTimelineProcedure is the fully-qualified name of the TimelineService's
	// MoveTimeline RPC.
	TimelineServiceMoveTimelineProcedure = "/timeline.TimelineService/MoveTimeline"
	// TimelineServiceGetTimelineProcedure is the fully-qualified name of the TimelineService's
	// GetTimeline RPC.
	TimelineServiceGetTimelineProcedure = "/timeline.TimelineService/GetTimeline"
)

// TimelineServiceClient is a client for the timeline.TimelineService service.
type TimelineServiceClient interface {
	MoveTimeline(context.Context, *connect.Request[_go.MoveTimelineRequest]) (*connect.Response[_go.MoveTimelineResponse], error)
	GetTimeline(context.Context, *connect.Request[_go.GetTimelineRequest]) (*connect.ServerStreamForClient[_go.GetTimelineResponse], error)
}

// NewTimelineServiceClient constructs a client for the timeline.TimelineService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTimelineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TimelineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	timelineServiceMethods := _go.File_timeline_proto.Services().ByName("TimelineService").Methods()
	return &timelineServiceClient{
		moveTimeline: connect.NewClient[_go.MoveTimelineRequest, _go.MoveTimelineResponse](
			httpClient,
			baseURL+TimelineServiceMoveTimelineProcedure,
			connect.WithSchema(timelineServiceMethods.ByName("MoveTimeline")),
			connect.WithClientOptions(opts...),
		),
		getTimeline: connect.NewClient[_go.GetTimelineRequest, _go.GetTimelineResponse](
			httpClient,
			baseURL+TimelineServiceGetTimelineProcedure,
			connect.WithSchema(timelineServiceMethods.ByName("GetTimeline")),
			connect.WithClientOptions(opts...),
		),
	}
}

// timelineServiceClient implements TimelineServiceClient.
type timelineServiceClient struct {
	moveTimeline *connect.Client[_go.MoveTimelineRequest, _go.MoveTimelineResponse]
	getTimeline  *connect.Client[_go.GetTimelineRequest, _go.GetTimelineResponse]
}

// MoveTimeline calls timeline.TimelineService.MoveTimeline.
func (c *timelineServiceClient) MoveTimeline(ctx context.Context, req *connect.Request[_go.MoveTimelineRequest]) (*connect.Response[_go.MoveTimelineResponse], error) {
	return c.moveTimeline.CallUnary(ctx, req)
}

// GetTimeline calls timeline.TimelineService.GetTimeline.
func (c *timelineServiceClient) GetTimeline(ctx context.Context, req *connect.Request[_go.GetTimelineRequest]) (*connect.ServerStreamForClient[_go.GetTimelineResponse], error) {
	return c.getTimeline.CallServerStream(ctx, req)
}

// TimelineServiceHandler is an implementation of the timeline.TimelineService service.
type TimelineServiceHandler interface {
	MoveTimeline(context.Context, *connect.Request[_go.MoveTimelineRequest]) (*connect.Response[_go.MoveTimelineResponse], error)
	GetTimeline(context.Context, *connect.Request[_go.GetTimelineRequest], *connect.ServerStream[_go.GetTimelineResponse]) error
}

// NewTimelineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTimelineServiceHandler(svc TimelineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	timelineServiceMethods := _go.File_timeline_proto.Services().ByName("TimelineService").Methods()
	timelineServiceMoveTimelineHandler := connect.NewUnaryHandler(
		TimelineServiceMoveTimelineProcedure,
		svc.MoveTimeline,
		connect.WithSchema(timelineServiceMethods.ByName("MoveTimeline")),
		connect.WithHandlerOptions(opts...),
	)
	timelineServiceGetTimelineHandler := connect.NewServerStreamHandler(
		TimelineServiceGetTimelineProcedure,
		svc.GetTimeline,
		connect.WithSchema(timelineServiceMethods.ByName("GetTimeline")),
		connect.WithHandlerOptions(opts...),
	)
	return "/timeline.TimelineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TimelineServiceMoveTimelineProcedure:
			timelineServiceMoveTimelineHandler.ServeHTTP(w, r)
		case TimelineServiceGetTimelineProcedure:
			timelineServiceGetTimelineHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTimelineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTimelineServiceHandler struct{}

func (UnimplementedTimelineServiceHandler) MoveTimeline(context.Context, *connect.Request[_go.MoveTimelineRequest]) (*connect.Response[_go.MoveTimelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("timeline.TimelineService.MoveTimeline is not implemented"))
}

func (UnimplementedTimelineServiceHandler) GetTimeline(context.Context, *connect.Request[_go.GetTimelineRequest], *connect.ServerStream[_go.GetTimelineResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("timeline.TimelineService.GetTimeline is not implemented"))
}
