// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: world.proto

package _goconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/projectqai/proto/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorldServiceName is the fully-qualified name of the WorldService service.
	WorldServiceName = "world.WorldService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorldServiceListEntitiesProcedure is the fully-qualified name of the WorldService's ListEntities
	// RPC.
	WorldServiceListEntitiesProcedure = "/world.WorldService/ListEntities"
	// WorldServiceGetEntityProcedure is the fully-qualified name of the WorldService's GetEntity RPC.
	WorldServiceGetEntityProcedure = "/world.WorldService/GetEntity"
	// WorldServiceWatchEntitiesProcedure is the fully-qualified name of the WorldService's
	// WatchEntities RPC.
	WorldServiceWatchEntitiesProcedure = "/world.WorldService/WatchEntities"
	// WorldServicePushProcedure is the fully-qualified name of the WorldService's Push RPC.
	WorldServicePushProcedure = "/world.WorldService/Push"
	// WorldServiceExpireEntityProcedure is the fully-qualified name of the WorldService's ExpireEntity
	// RPC.
	WorldServiceExpireEntityProcedure = "/world.WorldService/ExpireEntity"
	// WorldServiceGetLocalNodeProcedure is the fully-qualified name of the WorldService's GetLocalNode
	// RPC.
	WorldServiceGetLocalNodeProcedure = "/world.WorldService/GetLocalNode"
	// WorldServiceRunTaskProcedure is the fully-qualified name of the WorldService's RunTask RPC.
	WorldServiceRunTaskProcedure = "/world.WorldService/RunTask"
)

// WorldServiceClient is a client for the world.WorldService service.
type WorldServiceClient interface {
	// list entities present in the world once
	ListEntities(context.Context, *connect.Request[_go.ListEntitiesRequest]) (*connect.Response[_go.ListEntitiesResponse], error)
	// request every detail about one entity
	GetEntity(context.Context, *connect.Request[_go.GetEntityRequest]) (*connect.Response[_go.GetEntityResponse], error)
	// continously monitor entities present in the world. this is used by downstream C2.
	WatchEntities(context.Context, *connect.Request[_go.ListEntitiesRequest]) (*connect.ServerStreamForClient[_go.EntityChangeEvent], error)
	// Create or update an entity. Used by capabilities.
	Push(context.Context, *connect.Request[_go.EntityChangeRequest]) (*connect.Response[_go.EntityChangeResponse], error)
	// expire an entity, setting its lifetime.until to now
	ExpireEntity(context.Context, *connect.Request[_go.ExpireEntityRequest]) (*connect.Response[_go.ExpireEntityResponse], error)
	// get information about the local node the client is connected to
	GetLocalNode(context.Context, *connect.Request[_go.GetLocalNodeRequest]) (*connect.Response[_go.GetLocalNodeResponse], error)
	// create an instance of a specific task entity
	RunTask(context.Context, *connect.Request[_go.RunTaskRequest]) (*connect.Response[_go.RunTaskResponse], error)
}

// NewWorldServiceClient constructs a client for the world.WorldService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorldServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorldServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	worldServiceMethods := _go.File_world_proto.Services().ByName("WorldService").Methods()
	return &worldServiceClient{
		listEntities: connect.NewClient[_go.ListEntitiesRequest, _go.ListEntitiesResponse](
			httpClient,
			baseURL+WorldServiceListEntitiesProcedure,
			connect.WithSchema(worldServiceMethods.ByName("ListEntities")),
			connect.WithClientOptions(opts...),
		),
		getEntity: connect.NewClient[_go.GetEntityRequest, _go.GetEntityResponse](
			httpClient,
			baseURL+WorldServiceGetEntityProcedure,
			connect.WithSchema(worldServiceMethods.ByName("GetEntity")),
			connect.WithClientOptions(opts...),
		),
		watchEntities: connect.NewClient[_go.ListEntitiesRequest, _go.EntityChangeEvent](
			httpClient,
			baseURL+WorldServiceWatchEntitiesProcedure,
			connect.WithSchema(worldServiceMethods.ByName("WatchEntities")),
			connect.WithClientOptions(opts...),
		),
		push: connect.NewClient[_go.EntityChangeRequest, _go.EntityChangeResponse](
			httpClient,
			baseURL+WorldServicePushProcedure,
			connect.WithSchema(worldServiceMethods.ByName("Push")),
			connect.WithClientOptions(opts...),
		),
		expireEntity: connect.NewClient[_go.ExpireEntityRequest, _go.ExpireEntityResponse](
			httpClient,
			baseURL+WorldServiceExpireEntityProcedure,
			connect.WithSchema(worldServiceMethods.ByName("ExpireEntity")),
			connect.WithClientOptions(opts...),
		),
		getLocalNode: connect.NewClient[_go.GetLocalNodeRequest, _go.GetLocalNodeResponse](
			httpClient,
			baseURL+WorldServiceGetLocalNodeProcedure,
			connect.WithSchema(worldServiceMethods.ByName("GetLocalNode")),
			connect.WithClientOptions(opts...),
		),
		runTask: connect.NewClient[_go.RunTaskRequest, _go.RunTaskResponse](
			httpClient,
			baseURL+WorldServiceRunTaskProcedure,
			connect.WithSchema(worldServiceMethods.ByName("RunTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// worldServiceClient implements WorldServiceClient.
type worldServiceClient struct {
	listEntities  *connect.Client[_go.ListEntitiesRequest, _go.ListEntitiesResponse]
	getEntity     *connect.Client[_go.GetEntityRequest, _go.GetEntityResponse]
	watchEntities *connect.Client[_go.ListEntitiesRequest, _go.EntityChangeEvent]
	push          *connect.Client[_go.EntityChangeRequest, _go.EntityChangeResponse]
	expireEntity  *connect.Client[_go.ExpireEntityRequest, _go.ExpireEntityResponse]
	getLocalNode  *connect.Client[_go.GetLocalNodeRequest, _go.GetLocalNodeResponse]
	runTask       *connect.Client[_go.RunTaskRequest, _go.RunTaskResponse]
}

// ListEntities calls world.WorldService.ListEntities.
func (c *worldServiceClient) ListEntities(ctx context.Context, req *connect.Request[_go.ListEntitiesRequest]) (*connect.Response[_go.ListEntitiesResponse], error) {
	return c.listEntities.CallUnary(ctx, req)
}

// GetEntity calls world.WorldService.GetEntity.
func (c *worldServiceClient) GetEntity(ctx context.Context, req *connect.Request[_go.GetEntityRequest]) (*connect.Response[_go.GetEntityResponse], error) {
	return c.getEntity.CallUnary(ctx, req)
}

// WatchEntities calls world.WorldService.WatchEntities.
func (c *worldServiceClient) WatchEntities(ctx context.Context, req *connect.Request[_go.ListEntitiesRequest]) (*connect.ServerStreamForClient[_go.EntityChangeEvent], error) {
	return c.watchEntities.CallServerStream(ctx, req)
}

// Push calls world.WorldService.Push.
func (c *worldServiceClient) Push(ctx context.Context, req *connect.Request[_go.EntityChangeRequest]) (*connect.Response[_go.EntityChangeResponse], error) {
	return c.push.CallUnary(ctx, req)
}

// ExpireEntity calls world.WorldService.ExpireEntity.
func (c *worldServiceClient) ExpireEntity(ctx context.Context, req *connect.Request[_go.ExpireEntityRequest]) (*connect.Response[_go.ExpireEntityResponse], error) {
	return c.expireEntity.CallUnary(ctx, req)
}

// GetLocalNode calls world.WorldService.GetLocalNode.
func (c *worldServiceClient) GetLocalNode(ctx context.Context, req *connect.Request[_go.GetLocalNodeRequest]) (*connect.Response[_go.GetLocalNodeResponse], error) {
	return c.getLocalNode.CallUnary(ctx, req)
}

// RunTask calls world.WorldService.RunTask.
func (c *worldServiceClient) RunTask(ctx context.Context, req *connect.Request[_go.RunTaskRequest]) (*connect.Response[_go.RunTaskResponse], error) {
	return c.runTask.CallUnary(ctx, req)
}

// WorldServiceHandler is an implementation of the world.WorldService service.
type WorldServiceHandler interface {
	// list entities present in the world once
	ListEntities(context.Context, *connect.Request[_go.ListEntitiesRequest]) (*connect.Response[_go.ListEntitiesResponse], error)
	// request every detail about one entity
	GetEntity(context.Context, *connect.Request[_go.GetEntityRequest]) (*connect.Response[_go.GetEntityResponse], error)
	// continously monitor entities present in the world. this is used by downstream C2.
	WatchEntities(context.Context, *connect.Request[_go.ListEntitiesRequest], *connect.ServerStream[_go.EntityChangeEvent]) error
	// Create or update an entity. Used by capabilities.
	Push(context.Context, *connect.Request[_go.EntityChangeRequest]) (*connect.Response[_go.EntityChangeResponse], error)
	// expire an entity, setting its lifetime.until to now
	ExpireEntity(context.Context, *connect.Request[_go.ExpireEntityRequest]) (*connect.Response[_go.ExpireEntityResponse], error)
	// get information about the local node the client is connected to
	GetLocalNode(context.Context, *connect.Request[_go.GetLocalNodeRequest]) (*connect.Response[_go.GetLocalNodeResponse], error)
	// create an instance of a specific task entity
	RunTask(context.Context, *connect.Request[_go.RunTaskRequest]) (*connect.Response[_go.RunTaskResponse], error)
}

// NewWorldServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorldServiceHandler(svc WorldServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	worldServiceMethods := _go.File_world_proto.Services().ByName("WorldService").Methods()
	worldServiceListEntitiesHandler := connect.NewUnaryHandler(
		WorldServiceListEntitiesProcedure,
		svc.ListEntities,
		connect.WithSchema(worldServiceMethods.ByName("ListEntities")),
		connect.WithHandlerOptions(opts...),
	)
	worldServiceGetEntityHandler := connect.NewUnaryHandler(
		WorldServiceGetEntityProcedure,
		svc.GetEntity,
		connect.WithSchema(worldServiceMethods.ByName("GetEntity")),
		connect.WithHandlerOptions(opts...),
	)
	worldServiceWatchEntitiesHandler := connect.NewServerStreamHandler(
		WorldServiceWatchEntitiesProcedure,
		svc.WatchEntities,
		connect.WithSchema(worldServiceMethods.ByName("WatchEntities")),
		connect.WithHandlerOptions(opts...),
	)
	worldServicePushHandler := connect.NewUnaryHandler(
		WorldServicePushProcedure,
		svc.Push,
		connect.WithSchema(worldServiceMethods.ByName("Push")),
		connect.WithHandlerOptions(opts...),
	)
	worldServiceExpireEntityHandler := connect.NewUnaryHandler(
		WorldServiceExpireEntityProcedure,
		svc.ExpireEntity,
		connect.WithSchema(worldServiceMethods.ByName("ExpireEntity")),
		connect.WithHandlerOptions(opts...),
	)
	worldServiceGetLocalNodeHandler := connect.NewUnaryHandler(
		WorldServiceGetLocalNodeProcedure,
		svc.GetLocalNode,
		connect.WithSchema(worldServiceMethods.ByName("GetLocalNode")),
		connect.WithHandlerOptions(opts...),
	)
	worldServiceRunTaskHandler := connect.NewUnaryHandler(
		WorldServiceRunTaskProcedure,
		svc.RunTask,
		connect.WithSchema(worldServiceMethods.ByName("RunTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/world.WorldService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorldServiceListEntitiesProcedure:
			worldServiceListEntitiesHandler.ServeHTTP(w, r)
		case WorldServiceGetEntityProcedure:
			worldServiceGetEntityHandler.ServeHTTP(w, r)
		case WorldServiceWatchEntitiesProcedure:
			worldServiceWatchEntitiesHandler.ServeHTTP(w, r)
		case WorldServicePushProcedure:
			worldServicePushHandler.ServeHTTP(w, r)
		case WorldServiceExpireEntityProcedure:
			worldServiceExpireEntityHandler.ServeHTTP(w, r)
		case WorldServiceGetLocalNodeProcedure:
			worldServiceGetLocalNodeHandler.ServeHTTP(w, r)
		case WorldServiceRunTaskProcedure:
			worldServiceRunTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorldServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorldServiceHandler struct{}

func (UnimplementedWorldServiceHandler) ListEntities(context.Context, *connect.Request[_go.ListEntitiesRequest]) (*connect.Response[_go.ListEntitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.ListEntities is not implemented"))
}

func (UnimplementedWorldServiceHandler) GetEntity(context.Context, *connect.Request[_go.GetEntityRequest]) (*connect.Response[_go.GetEntityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.GetEntity is not implemented"))
}

func (UnimplementedWorldServiceHandler) WatchEntities(context.Context, *connect.Request[_go.ListEntitiesRequest], *connect.ServerStream[_go.EntityChangeEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.WatchEntities is not implemented"))
}

func (UnimplementedWorldServiceHandler) Push(context.Context, *connect.Request[_go.EntityChangeRequest]) (*connect.Response[_go.EntityChangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.Push is not implemented"))
}

func (UnimplementedWorldServiceHandler) ExpireEntity(context.Context, *connect.Request[_go.ExpireEntityRequest]) (*connect.Response[_go.ExpireEntityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.ExpireEntity is not implemented"))
}

func (UnimplementedWorldServiceHandler) GetLocalNode(context.Context, *connect.Request[_go.GetLocalNodeRequest]) (*connect.Response[_go.GetLocalNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.GetLocalNode is not implemented"))
}

func (UnimplementedWorldServiceHandler) RunTask(context.Context, *connect.Request[_go.RunTaskRequest]) (*connect.Response[_go.RunTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("world.WorldService.RunTask is not implemented"))
}
