// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: geometry.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// a 2.5D point on the projected flat surface in WGS84
type PlanarPoint struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Longitude float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// height above ellipsoid (WGS84) in meters
	Altitude      *float64 `protobuf:"fixed64,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanarPoint) Reset() {
	*x = PlanarPoint{}
	mi := &file_geometry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanarPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanarPoint) ProtoMessage() {}

func (x *PlanarPoint) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanarPoint.ProtoReflect.Descriptor instead.
func (*PlanarPoint) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{0}
}

func (x *PlanarPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PlanarPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PlanarPoint) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

// a path with zero area on the projected flat surface
// a ring is considered to be closed when the first and last points are identical
type PlanarRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PlanarPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanarRing) Reset() {
	*x = PlanarRing{}
	mi := &file_geometry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanarRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanarRing) ProtoMessage() {}

func (x *PlanarRing) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanarRing.ProtoReflect.Descriptor instead.
func (*PlanarRing) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *PlanarRing) GetPoints() []*PlanarPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// / An area enclosed by a ring, with optional holes.
// / All rings must be closed (first point = last point)
type PlanarPolygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outer         *PlanarRing            `protobuf:"bytes,1,opt,name=outer,proto3" json:"outer,omitempty"`
	Holes         []*PlanarRing          `protobuf:"bytes,2,rep,name=holes,proto3" json:"holes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanarPolygon) Reset() {
	*x = PlanarPolygon{}
	mi := &file_geometry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanarPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanarPolygon) ProtoMessage() {}

func (x *PlanarPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanarPolygon.ProtoReflect.Descriptor instead.
func (*PlanarPolygon) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{2}
}

func (x *PlanarPolygon) GetOuter() *PlanarRing {
	if x != nil {
		return x.Outer
	}
	return nil
}

func (x *PlanarPolygon) GetHoles() []*PlanarRing {
	if x != nil {
		return x.Holes
	}
	return nil
}

// 2.5D geometry in WGS 84
type PlanarCircle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *PlanarPoint           `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusM       float64                `protobuf:"fixed64,2,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	InnerRadiusM  *float64               `protobuf:"fixed64,3,opt,name=inner_radius_m,json=innerRadiusM,proto3,oneof" json:"inner_radius_m,omitempty"` // omit for solid circle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanarCircle) Reset() {
	*x = PlanarCircle{}
	mi := &file_geometry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanarCircle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanarCircle) ProtoMessage() {}

func (x *PlanarCircle) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanarCircle.ProtoReflect.Descriptor instead.
func (*PlanarCircle) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{3}
}

func (x *PlanarCircle) GetCenter() *PlanarPoint {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *PlanarCircle) GetRadiusM() float64 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *PlanarCircle) GetInnerRadiusM() float64 {
	if x != nil && x.InnerRadiusM != nil {
		return *x.InnerRadiusM
	}
	return 0
}

type PlanarGeometry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Plane:
	//
	//	*PlanarGeometry_Point
	//	*PlanarGeometry_Line
	//	*PlanarGeometry_Polygon
	//	*PlanarGeometry_Circle
	Plane         isPlanarGeometry_Plane `protobuf_oneof:"plane"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanarGeometry) Reset() {
	*x = PlanarGeometry{}
	mi := &file_geometry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanarGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanarGeometry) ProtoMessage() {}

func (x *PlanarGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanarGeometry.ProtoReflect.Descriptor instead.
func (*PlanarGeometry) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{4}
}

func (x *PlanarGeometry) GetPlane() isPlanarGeometry_Plane {
	if x != nil {
		return x.Plane
	}
	return nil
}

func (x *PlanarGeometry) GetPoint() *PlanarPoint {
	if x != nil {
		if x, ok := x.Plane.(*PlanarGeometry_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *PlanarGeometry) GetLine() *PlanarRing {
	if x != nil {
		if x, ok := x.Plane.(*PlanarGeometry_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *PlanarGeometry) GetPolygon() *PlanarPolygon {
	if x != nil {
		if x, ok := x.Plane.(*PlanarGeometry_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

func (x *PlanarGeometry) GetCircle() *PlanarCircle {
	if x != nil {
		if x, ok := x.Plane.(*PlanarGeometry_Circle); ok {
			return x.Circle
		}
	}
	return nil
}

type isPlanarGeometry_Plane interface {
	isPlanarGeometry_Plane()
}

type PlanarGeometry_Point struct {
	Point *PlanarPoint `protobuf:"bytes,1,opt,name=point,proto3,oneof"`
}

type PlanarGeometry_Line struct {
	Line *PlanarRing `protobuf:"bytes,2,opt,name=line,proto3,oneof"`
}

type PlanarGeometry_Polygon struct {
	Polygon *PlanarPolygon `protobuf:"bytes,3,opt,name=polygon,proto3,oneof"`
}

type PlanarGeometry_Circle struct {
	Circle *PlanarCircle `protobuf:"bytes,4,opt,name=circle,proto3,oneof"`
}

func (*PlanarGeometry_Point) isPlanarGeometry_Plane() {}

func (*PlanarGeometry_Line) isPlanarGeometry_Plane() {}

func (*PlanarGeometry_Polygon) isPlanarGeometry_Plane() {}

func (*PlanarGeometry_Circle) isPlanarGeometry_Plane() {}

type LocalPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EastM         float64                `protobuf:"fixed64,1,opt,name=east_m,json=eastM,proto3" json:"east_m,omitempty"`
	NorthM        float64                `protobuf:"fixed64,2,opt,name=north_m,json=northM,proto3" json:"north_m,omitempty"`
	UpM           *float64               `protobuf:"fixed64,3,opt,name=up_m,json=upM,proto3,oneof" json:"up_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalPoint) Reset() {
	*x = LocalPoint{}
	mi := &file_geometry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPoint) ProtoMessage() {}

func (x *LocalPoint) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPoint.ProtoReflect.Descriptor instead.
func (*LocalPoint) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{5}
}

func (x *LocalPoint) GetEastM() float64 {
	if x != nil {
		return x.EastM
	}
	return 0
}

func (x *LocalPoint) GetNorthM() float64 {
	if x != nil {
		return x.NorthM
	}
	return 0
}

func (x *LocalPoint) GetUpM() float64 {
	if x != nil && x.UpM != nil {
		return *x.UpM
	}
	return 0
}

type LocalRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*LocalPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRing) Reset() {
	*x = LocalRing{}
	mi := &file_geometry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRing) ProtoMessage() {}

func (x *LocalRing) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRing.ProtoReflect.Descriptor instead.
func (*LocalRing) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{6}
}

func (x *LocalRing) GetPoints() []*LocalPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type LocalPolygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outer         *LocalRing             `protobuf:"bytes,1,opt,name=outer,proto3" json:"outer,omitempty"`
	Holes         []*LocalRing           `protobuf:"bytes,2,rep,name=holes,proto3" json:"holes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalPolygon) Reset() {
	*x = LocalPolygon{}
	mi := &file_geometry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPolygon) ProtoMessage() {}

func (x *LocalPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPolygon.ProtoReflect.Descriptor instead.
func (*LocalPolygon) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{7}
}

func (x *LocalPolygon) GetOuter() *LocalRing {
	if x != nil {
		return x.Outer
	}
	return nil
}

func (x *LocalPolygon) GetHoles() []*LocalRing {
	if x != nil {
		return x.Holes
	}
	return nil
}

type LocalCircle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *LocalPoint            `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusM       float64                `protobuf:"fixed64,2,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	InnerRadiusM  *float64               `protobuf:"fixed64,3,opt,name=inner_radius_m,json=innerRadiusM,proto3,oneof" json:"inner_radius_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalCircle) Reset() {
	*x = LocalCircle{}
	mi := &file_geometry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCircle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCircle) ProtoMessage() {}

func (x *LocalCircle) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCircle.ProtoReflect.Descriptor instead.
func (*LocalCircle) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{8}
}

func (x *LocalCircle) GetCenter() *LocalPoint {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *LocalCircle) GetRadiusM() float64 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *LocalCircle) GetInnerRadiusM() float64 {
	if x != nil && x.InnerRadiusM != nil {
		return *x.InnerRadiusM
	}
	return 0
}

type LocalGeometry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Shape:
	//
	//	*LocalGeometry_Point
	//	*LocalGeometry_Line
	//	*LocalGeometry_Polygon
	//	*LocalGeometry_Circle
	Shape         isLocalGeometry_Shape `protobuf_oneof:"shape"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalGeometry) Reset() {
	*x = LocalGeometry{}
	mi := &file_geometry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalGeometry) ProtoMessage() {}

func (x *LocalGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalGeometry.ProtoReflect.Descriptor instead.
func (*LocalGeometry) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{9}
}

func (x *LocalGeometry) GetShape() isLocalGeometry_Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *LocalGeometry) GetPoint() *LocalPoint {
	if x != nil {
		if x, ok := x.Shape.(*LocalGeometry_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *LocalGeometry) GetLine() *LocalRing {
	if x != nil {
		if x, ok := x.Shape.(*LocalGeometry_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *LocalGeometry) GetPolygon() *LocalPolygon {
	if x != nil {
		if x, ok := x.Shape.(*LocalGeometry_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

func (x *LocalGeometry) GetCircle() *LocalCircle {
	if x != nil {
		if x, ok := x.Shape.(*LocalGeometry_Circle); ok {
			return x.Circle
		}
	}
	return nil
}

type isLocalGeometry_Shape interface {
	isLocalGeometry_Shape()
}

type LocalGeometry_Point struct {
	Point *LocalPoint `protobuf:"bytes,1,opt,name=point,proto3,oneof"`
}

type LocalGeometry_Line struct {
	Line *LocalRing `protobuf:"bytes,2,opt,name=line,proto3,oneof"`
}

type LocalGeometry_Polygon struct {
	Polygon *LocalPolygon `protobuf:"bytes,3,opt,name=polygon,proto3,oneof"`
}

type LocalGeometry_Circle struct {
	Circle *LocalCircle `protobuf:"bytes,4,opt,name=circle,proto3,oneof"`
}

func (*LocalGeometry_Point) isLocalGeometry_Shape() {}

func (*LocalGeometry_Line) isLocalGeometry_Shape() {}

func (*LocalGeometry_Polygon) isLocalGeometry_Shape() {}

func (*LocalGeometry_Circle) isLocalGeometry_Shape() {}

var File_geometry_proto protoreflect.FileDescriptor

const file_geometry_proto_rawDesc = "" +
	"\n" +
	"\x0egeometry.proto\x12\x05world\"u\n" +
	"\vPlanarPoint\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1f\n" +
	"\baltitude\x18\x03 \x01(\x01H\x00R\baltitude\x88\x01\x01B\v\n" +
	"\t_altitude\"8\n" +
	"\n" +
	"PlanarRing\x12*\n" +
	"\x06points\x18\x01 \x03(\v2\x12.world.PlanarPointR\x06points\"a\n" +
	"\rPlanarPolygon\x12'\n" +
	"\x05outer\x18\x01 \x01(\v2\x11.world.PlanarRingR\x05outer\x12'\n" +
	"\x05holes\x18\x02 \x03(\v2\x11.world.PlanarRingR\x05holes\"\x93\x01\n" +
	"\fPlanarCircle\x12*\n" +
	"\x06center\x18\x01 \x01(\v2\x12.world.PlanarPointR\x06center\x12\x19\n" +
	"\bradius_m\x18\x02 \x01(\x01R\aradiusM\x12)\n" +
	"\x0einner_radius_m\x18\x03 \x01(\x01H\x00R\finnerRadiusM\x88\x01\x01B\x11\n" +
	"\x0f_inner_radius_m\"\xcf\x01\n" +
	"\x0ePlanarGeometry\x12*\n" +
	"\x05point\x18\x01 \x01(\v2\x12.world.PlanarPointH\x00R\x05point\x12'\n" +
	"\x04line\x18\x02 \x01(\v2\x11.world.PlanarRingH\x00R\x04line\x120\n" +
	"\apolygon\x18\x03 \x01(\v2\x14.world.PlanarPolygonH\x00R\apolygon\x12-\n" +
	"\x06circle\x18\x04 \x01(\v2\x13.world.PlanarCircleH\x00R\x06circleB\a\n" +
	"\x05plane\"]\n" +
	"\n" +
	"LocalPoint\x12\x15\n" +
	"\x06east_m\x18\x01 \x01(\x01R\x05eastM\x12\x17\n" +
	"\anorth_m\x18\x02 \x01(\x01R\x06northM\x12\x16\n" +
	"\x04up_m\x18\x03 \x01(\x01H\x00R\x03upM\x88\x01\x01B\a\n" +
	"\x05_up_m\"6\n" +
	"\tLocalRing\x12)\n" +
	"\x06points\x18\x01 \x03(\v2\x11.world.LocalPointR\x06points\"^\n" +
	"\fLocalPolygon\x12&\n" +
	"\x05outer\x18\x01 \x01(\v2\x10.world.LocalRingR\x05outer\x12&\n" +
	"\x05holes\x18\x02 \x03(\v2\x10.world.LocalRingR\x05holes\"\x91\x01\n" +
	"\vLocalCircle\x12)\n" +
	"\x06center\x18\x01 \x01(\v2\x11.world.LocalPointR\x06center\x12\x19\n" +
	"\bradius_m\x18\x02 \x01(\x01R\aradiusM\x12)\n" +
	"\x0einner_radius_m\x18\x03 \x01(\x01H\x00R\finnerRadiusM\x88\x01\x01B\x11\n" +
	"\x0f_inner_radius_m\"\xca\x01\n" +
	"\rLocalGeometry\x12)\n" +
	"\x05point\x18\x01 \x01(\v2\x11.world.LocalPointH\x00R\x05point\x12&\n" +
	"\x04line\x18\x02 \x01(\v2\x10.world.LocalRingH\x00R\x04line\x12/\n" +
	"\apolygon\x18\x03 \x01(\v2\x13.world.LocalPolygonH\x00R\apolygon\x12,\n" +
	"\x06circle\x18\x04 \x01(\v2\x12.world.LocalCircleH\x00R\x06circleB\a\n" +
	"\x05shapeB Z\x1egithub.com/projectqai/proto/gob\x06proto3"

var (
	file_geometry_proto_rawDescOnce sync.Once
	file_geometry_proto_rawDescData []byte
)

func file_geometry_proto_rawDescGZIP() []byte {
	file_geometry_proto_rawDescOnce.Do(func() {
		file_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geometry_proto_rawDesc), len(file_geometry_proto_rawDesc)))
	})
	return file_geometry_proto_rawDescData
}

var file_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_geometry_proto_goTypes = []any{
	(*PlanarPoint)(nil),    // 0: world.PlanarPoint
	(*PlanarRing)(nil),     // 1: world.PlanarRing
	(*PlanarPolygon)(nil),  // 2: world.PlanarPolygon
	(*PlanarCircle)(nil),   // 3: world.PlanarCircle
	(*PlanarGeometry)(nil), // 4: world.PlanarGeometry
	(*LocalPoint)(nil),     // 5: world.LocalPoint
	(*LocalRing)(nil),      // 6: world.LocalRing
	(*LocalPolygon)(nil),   // 7: world.LocalPolygon
	(*LocalCircle)(nil),    // 8: world.LocalCircle
	(*LocalGeometry)(nil),  // 9: world.LocalGeometry
}
var file_geometry_proto_depIdxs = []int32{
	0,  // 0: world.PlanarRing.points:type_name -> world.PlanarPoint
	1,  // 1: world.PlanarPolygon.outer:type_name -> world.PlanarRing
	1,  // 2: world.PlanarPolygon.holes:type_name -> world.PlanarRing
	0,  // 3: world.PlanarCircle.center:type_name -> world.PlanarPoint
	0,  // 4: world.PlanarGeometry.point:type_name -> world.PlanarPoint
	1,  // 5: world.PlanarGeometry.line:type_name -> world.PlanarRing
	2,  // 6: world.PlanarGeometry.polygon:type_name -> world.PlanarPolygon
	3,  // 7: world.PlanarGeometry.circle:type_name -> world.PlanarCircle
	5,  // 8: world.LocalRing.points:type_name -> world.LocalPoint
	6,  // 9: world.LocalPolygon.outer:type_name -> world.LocalRing
	6,  // 10: world.LocalPolygon.holes:type_name -> world.LocalRing
	5,  // 11: world.LocalCircle.center:type_name -> world.LocalPoint
	5,  // 12: world.LocalGeometry.point:type_name -> world.LocalPoint
	6,  // 13: world.LocalGeometry.line:type_name -> world.LocalRing
	7,  // 14: world.LocalGeometry.polygon:type_name -> world.LocalPolygon
	8,  // 15: world.LocalGeometry.circle:type_name -> world.LocalCircle
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_geometry_proto_init() }
func file_geometry_proto_init() {
	if File_geometry_proto != nil {
		return
	}
	file_geometry_proto_msgTypes[0].OneofWrappers = []any{}
	file_geometry_proto_msgTypes[3].OneofWrappers = []any{}
	file_geometry_proto_msgTypes[4].OneofWrappers = []any{
		(*PlanarGeometry_Point)(nil),
		(*PlanarGeometry_Line)(nil),
		(*PlanarGeometry_Polygon)(nil),
		(*PlanarGeometry_Circle)(nil),
	}
	file_geometry_proto_msgTypes[5].OneofWrappers = []any{}
	file_geometry_proto_msgTypes[8].OneofWrappers = []any{}
	file_geometry_proto_msgTypes[9].OneofWrappers = []any{
		(*LocalGeometry_Point)(nil),
		(*LocalGeometry_Line)(nil),
		(*LocalGeometry_Polygon)(nil),
		(*LocalGeometry_Circle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geometry_proto_rawDesc), len(file_geometry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geometry_proto_goTypes,
		DependencyIndexes: file_geometry_proto_depIdxs,
		MessageInfos:      file_geometry_proto_msgTypes,
	}.Build()
	File_geometry_proto = out.File
	file_geometry_proto_goTypes = nil
	file_geometry_proto_depIdxs = nil
}
