// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: manualcontrol.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManualControlInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Axes          *ManualControlAxes     `protobuf:"bytes,1,opt,name=axes,proto3" json:"axes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualControlInput) Reset() {
	*x = ManualControlInput{}
	mi := &file_manualcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualControlInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualControlInput) ProtoMessage() {}

func (x *ManualControlInput) ProtoReflect() protoreflect.Message {
	mi := &file_manualcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualControlInput.ProtoReflect.Descriptor instead.
func (*ManualControlInput) Descriptor() ([]byte, []int) {
	return file_manualcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *ManualControlInput) GetAxes() *ManualControlAxes {
	if x != nil {
		return x.Axes
	}
	return nil
}

type ManualControlAxes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forward       *float32               `protobuf:"fixed32,1,opt,name=forward,proto3,oneof" json:"forward,omitempty"`
	Right         *float32               `protobuf:"fixed32,2,opt,name=right,proto3,oneof" json:"right,omitempty"`
	Up            *float32               `protobuf:"fixed32,3,opt,name=up,proto3,oneof" json:"up,omitempty"`
	Yaw           *float32               `protobuf:"fixed32,4,opt,name=yaw,proto3,oneof" json:"yaw,omitempty"`
	Pitch         *float32               `protobuf:"fixed32,5,opt,name=pitch,proto3,oneof" json:"pitch,omitempty"`
	Roll          *float32               `protobuf:"fixed32,6,opt,name=roll,proto3,oneof" json:"roll,omitempty"`
	Pan           *float32               `protobuf:"fixed32,7,opt,name=pan,proto3,oneof" json:"pan,omitempty"`
	Tilt          *float32               `protobuf:"fixed32,8,opt,name=tilt,proto3,oneof" json:"tilt,omitempty"`
	Zoom          *float32               `protobuf:"fixed32,9,opt,name=zoom,proto3,oneof" json:"zoom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualControlAxes) Reset() {
	*x = ManualControlAxes{}
	mi := &file_manualcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualControlAxes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualControlAxes) ProtoMessage() {}

func (x *ManualControlAxes) ProtoReflect() protoreflect.Message {
	mi := &file_manualcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualControlAxes.ProtoReflect.Descriptor instead.
func (*ManualControlAxes) Descriptor() ([]byte, []int) {
	return file_manualcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *ManualControlAxes) GetForward() float32 {
	if x != nil && x.Forward != nil {
		return *x.Forward
	}
	return 0
}

func (x *ManualControlAxes) GetRight() float32 {
	if x != nil && x.Right != nil {
		return *x.Right
	}
	return 0
}

func (x *ManualControlAxes) GetUp() float32 {
	if x != nil && x.Up != nil {
		return *x.Up
	}
	return 0
}

func (x *ManualControlAxes) GetYaw() float32 {
	if x != nil && x.Yaw != nil {
		return *x.Yaw
	}
	return 0
}

func (x *ManualControlAxes) GetPitch() float32 {
	if x != nil && x.Pitch != nil {
		return *x.Pitch
	}
	return 0
}

func (x *ManualControlAxes) GetRoll() float32 {
	if x != nil && x.Roll != nil {
		return *x.Roll
	}
	return 0
}

func (x *ManualControlAxes) GetPan() float32 {
	if x != nil && x.Pan != nil {
		return *x.Pan
	}
	return 0
}

func (x *ManualControlAxes) GetTilt() float32 {
	if x != nil && x.Tilt != nil {
		return *x.Tilt
	}
	return 0
}

func (x *ManualControlAxes) GetZoom() float32 {
	if x != nil && x.Zoom != nil {
		return *x.Zoom
	}
	return 0
}

var File_manualcontrol_proto protoreflect.FileDescriptor

const file_manualcontrol_proto_rawDesc = "" +
	"\n" +
	"\x13manualcontrol.proto\x12\x05world\"B\n" +
	"\x12ManualControlInput\x12,\n" +
	"\x04axes\x18\x01 \x01(\v2\x18.world.ManualControlAxesR\x04axes\"\xc8\x02\n" +
	"\x11ManualControlAxes\x12\x1d\n" +
	"\aforward\x18\x01 \x01(\x02H\x00R\aforward\x88\x01\x01\x12\x19\n" +
	"\x05right\x18\x02 \x01(\x02H\x01R\x05right\x88\x01\x01\x12\x13\n" +
	"\x02up\x18\x03 \x01(\x02H\x02R\x02up\x88\x01\x01\x12\x15\n" +
	"\x03yaw\x18\x04 \x01(\x02H\x03R\x03yaw\x88\x01\x01\x12\x19\n" +
	"\x05pitch\x18\x05 \x01(\x02H\x04R\x05pitch\x88\x01\x01\x12\x17\n" +
	"\x04roll\x18\x06 \x01(\x02H\x05R\x04roll\x88\x01\x01\x12\x15\n" +
	"\x03pan\x18\a \x01(\x02H\x06R\x03pan\x88\x01\x01\x12\x17\n" +
	"\x04tilt\x18\b \x01(\x02H\aR\x04tilt\x88\x01\x01\x12\x17\n" +
	"\x04zoom\x18\t \x01(\x02H\bR\x04zoom\x88\x01\x01B\n" +
	"\n" +
	"\b_forwardB\b\n" +
	"\x06_rightB\x05\n" +
	"\x03_upB\x06\n" +
	"\x04_yawB\b\n" +
	"\x06_pitchB\a\n" +
	"\x05_rollB\x06\n" +
	"\x04_panB\a\n" +
	"\x05_tiltB\a\n" +
	"\x05_zoomB Z\x1egithub.com/projectqai/proto/gob\x06proto3"

var (
	file_manualcontrol_proto_rawDescOnce sync.Once
	file_manualcontrol_proto_rawDescData []byte
)

func file_manualcontrol_proto_rawDescGZIP() []byte {
	file_manualcontrol_proto_rawDescOnce.Do(func() {
		file_manualcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manualcontrol_proto_rawDesc), len(file_manualcontrol_proto_rawDesc)))
	})
	return file_manualcontrol_proto_rawDescData
}

var file_manualcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_manualcontrol_proto_goTypes = []any{
	(*ManualControlInput)(nil), // 0: world.ManualControlInput
	(*ManualControlAxes)(nil),  // 1: world.ManualControlAxes
}
var file_manualcontrol_proto_depIdxs = []int32{
	1, // 0: world.ManualControlInput.axes:type_name -> world.ManualControlAxes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_manualcontrol_proto_init() }
func file_manualcontrol_proto_init() {
	if File_manualcontrol_proto != nil {
		return
	}
	file_manualcontrol_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manualcontrol_proto_rawDesc), len(file_manualcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manualcontrol_proto_goTypes,
		DependencyIndexes: file_manualcontrol_proto_depIdxs,
		MessageInfos:      file_manualcontrol_proto_msgTypes,
	}.Build()
	File_manualcontrol_proto = out.File
	file_manualcontrol_proto_goTypes = nil
	file_manualcontrol_proto_depIdxs = nil
}
