// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tasking.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskableTarget struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Position      *TaskableTargetPosition  `protobuf:"bytes,1,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Waypoints     *TaskableTargetWaypoints `protobuf:"bytes,2,opt,name=waypoints,proto3,oneof" json:"waypoints,omitempty"`
	Entity        *TaskableTargetEntity    `protobuf:"bytes,3,opt,name=entity,proto3,oneof" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskableTarget) Reset() {
	*x = TaskableTarget{}
	mi := &file_tasking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskableTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskableTarget) ProtoMessage() {}

func (x *TaskableTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskableTarget.ProtoReflect.Descriptor instead.
func (*TaskableTarget) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{0}
}

func (x *TaskableTarget) GetPosition() *TaskableTargetPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TaskableTarget) GetWaypoints() *TaskableTargetWaypoints {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *TaskableTarget) GetEntity() *TaskableTargetEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type TaskableTargetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskableTargetPosition) Reset() {
	*x = TaskableTargetPosition{}
	mi := &file_tasking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskableTargetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskableTargetPosition) ProtoMessage() {}

func (x *TaskableTargetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskableTargetPosition.ProtoReflect.Descriptor instead.
func (*TaskableTargetPosition) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{1}
}

type TaskableTargetWaypoints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// maximum number of waypoints. default unbounded.
	Max *uint32 `protobuf:"varint,1,opt,name=max,proto3,oneof" json:"max,omitempty"`
	// the waypoints form a closed loop (last connects back to first), e.g. patrol.
	Loop          *bool `protobuf:"varint,2,opt,name=loop,proto3,oneof" json:"loop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskableTargetWaypoints) Reset() {
	*x = TaskableTargetWaypoints{}
	mi := &file_tasking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskableTargetWaypoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskableTargetWaypoints) ProtoMessage() {}

func (x *TaskableTargetWaypoints) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskableTargetWaypoints.ProtoReflect.Descriptor instead.
func (*TaskableTargetWaypoints) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{2}
}

func (x *TaskableTargetWaypoints) GetMax() uint32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *TaskableTargetWaypoints) GetLoop() bool {
	if x != nil && x.Loop != nil {
		return *x.Loop
	}
	return false
}

type TaskableTargetEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Max           *uint32                `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskableTargetEntity) Reset() {
	*x = TaskableTargetEntity{}
	mi := &file_tasking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskableTargetEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskableTargetEntity) ProtoMessage() {}

func (x *TaskableTargetEntity) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskableTargetEntity.ProtoReflect.Descriptor instead.
func (*TaskableTargetEntity) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{3}
}

func (x *TaskableTargetEntity) GetMax() uint32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type TaskExecutionTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TaskExecutionTarget_Position
	//	*TaskExecutionTarget_Waypoints
	//	*TaskExecutionTarget_Entity
	Kind          isTaskExecutionTarget_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionTarget) Reset() {
	*x = TaskExecutionTarget{}
	mi := &file_tasking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionTarget) ProtoMessage() {}

func (x *TaskExecutionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionTarget.ProtoReflect.Descriptor instead.
func (*TaskExecutionTarget) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{4}
}

func (x *TaskExecutionTarget) GetKind() isTaskExecutionTarget_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TaskExecutionTarget) GetPosition() *PlanarPoint {
	if x != nil {
		if x, ok := x.Kind.(*TaskExecutionTarget_Position); ok {
			return x.Position
		}
	}
	return nil
}

func (x *TaskExecutionTarget) GetWaypoints() *TaskExecutionTargetWaypoints {
	if x != nil {
		if x, ok := x.Kind.(*TaskExecutionTarget_Waypoints); ok {
			return x.Waypoints
		}
	}
	return nil
}

func (x *TaskExecutionTarget) GetEntity() *TaskExecutionTargetEntity {
	if x != nil {
		if x, ok := x.Kind.(*TaskExecutionTarget_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

type isTaskExecutionTarget_Kind interface {
	isTaskExecutionTarget_Kind()
}

type TaskExecutionTarget_Position struct {
	Position *PlanarPoint `protobuf:"bytes,1,opt,name=position,proto3,oneof"`
}

type TaskExecutionTarget_Waypoints struct {
	Waypoints *TaskExecutionTargetWaypoints `protobuf:"bytes,2,opt,name=waypoints,proto3,oneof"`
}

type TaskExecutionTarget_Entity struct {
	Entity *TaskExecutionTargetEntity `protobuf:"bytes,3,opt,name=entity,proto3,oneof"`
}

func (*TaskExecutionTarget_Position) isTaskExecutionTarget_Kind() {}

func (*TaskExecutionTarget_Waypoints) isTaskExecutionTarget_Kind() {}

func (*TaskExecutionTarget_Entity) isTaskExecutionTarget_Kind() {}

type TaskExecutionTargetWaypoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waypoint      []*PlanarPoint         `protobuf:"bytes,1,rep,name=waypoint,proto3" json:"waypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionTargetWaypoints) Reset() {
	*x = TaskExecutionTargetWaypoints{}
	mi := &file_tasking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionTargetWaypoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionTargetWaypoints) ProtoMessage() {}

func (x *TaskExecutionTargetWaypoints) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionTargetWaypoints.ProtoReflect.Descriptor instead.
func (*TaskExecutionTargetWaypoints) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{5}
}

func (x *TaskExecutionTargetWaypoints) GetWaypoint() []*PlanarPoint {
	if x != nil {
		return x.Waypoint
	}
	return nil
}

type TaskExecutionTargetEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        []string               `protobuf:"bytes,1,rep,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionTargetEntity) Reset() {
	*x = TaskExecutionTargetEntity{}
	mi := &file_tasking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionTargetEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionTargetEntity) ProtoMessage() {}

func (x *TaskExecutionTargetEntity) ProtoReflect() protoreflect.Message {
	mi := &file_tasking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionTargetEntity.ProtoReflect.Descriptor instead.
func (*TaskExecutionTargetEntity) Descriptor() ([]byte, []int) {
	return file_tasking_proto_rawDescGZIP(), []int{6}
}

func (x *TaskExecutionTargetEntity) GetEntity() []string {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_tasking_proto protoreflect.FileDescriptor

const file_tasking_proto_rawDesc = "" +
	"\n" +
	"\rtasking.proto\x12\x05world\x1a\x0egeometry.proto\"\xf3\x01\n" +
	"\x0eTaskableTarget\x12>\n" +
	"\bposition\x18\x01 \x01(\v2\x1d.world.TaskableTargetPositionH\x00R\bposition\x88\x01\x01\x12A\n" +
	"\twaypoints\x18\x02 \x01(\v2\x1e.world.TaskableTargetWaypointsH\x01R\twaypoints\x88\x01\x01\x128\n" +
	"\x06entity\x18\x03 \x01(\v2\x1b.world.TaskableTargetEntityH\x02R\x06entity\x88\x01\x01B\v\n" +
	"\t_positionB\f\n" +
	"\n" +
	"_waypointsB\t\n" +
	"\a_entity\"\x18\n" +
	"\x16TaskableTargetPosition\"Z\n" +
	"\x17TaskableTargetWaypoints\x12\x15\n" +
	"\x03max\x18\x01 \x01(\rH\x00R\x03max\x88\x01\x01\x12\x17\n" +
	"\x04loop\x18\x02 \x01(\bH\x01R\x04loop\x88\x01\x01B\x06\n" +
	"\x04_maxB\a\n" +
	"\x05_loop\"5\n" +
	"\x14TaskableTargetEntity\x12\x15\n" +
	"\x03max\x18\x02 \x01(\rH\x00R\x03max\x88\x01\x01B\x06\n" +
	"\x04_max\"\xd0\x01\n" +
	"\x13TaskExecutionTarget\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x12.world.PlanarPointH\x00R\bposition\x12C\n" +
	"\twaypoints\x18\x02 \x01(\v2#.world.TaskExecutionTargetWaypointsH\x00R\twaypoints\x12:\n" +
	"\x06entity\x18\x03 \x01(\v2 .world.TaskExecutionTargetEntityH\x00R\x06entityB\x06\n" +
	"\x04kind\"N\n" +
	"\x1cTaskExecutionTargetWaypoints\x12.\n" +
	"\bwaypoint\x18\x01 \x03(\v2\x12.world.PlanarPointR\bwaypoint\"3\n" +
	"\x19TaskExecutionTargetEntity\x12\x16\n" +
	"\x06entity\x18\x01 \x03(\tR\x06entityB Z\x1egithub.com/projectqai/proto/gob\x06proto3"

var (
	file_tasking_proto_rawDescOnce sync.Once
	file_tasking_proto_rawDescData []byte
)

func file_tasking_proto_rawDescGZIP() []byte {
	file_tasking_proto_rawDescOnce.Do(func() {
		file_tasking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasking_proto_rawDesc), len(file_tasking_proto_rawDesc)))
	})
	return file_tasking_proto_rawDescData
}

var file_tasking_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tasking_proto_goTypes = []any{
	(*TaskableTarget)(nil),               // 0: world.TaskableTarget
	(*TaskableTargetPosition)(nil),       // 1: world.TaskableTargetPosition
	(*TaskableTargetWaypoints)(nil),      // 2: world.TaskableTargetWaypoints
	(*TaskableTargetEntity)(nil),         // 3: world.TaskableTargetEntity
	(*TaskExecutionTarget)(nil),          // 4: world.TaskExecutionTarget
	(*TaskExecutionTargetWaypoints)(nil), // 5: world.TaskExecutionTargetWaypoints
	(*TaskExecutionTargetEntity)(nil),    // 6: world.TaskExecutionTargetEntity
	(*PlanarPoint)(nil),                  // 7: world.PlanarPoint
}
var file_tasking_proto_depIdxs = []int32{
	1, // 0: world.TaskableTarget.position:type_name -> world.TaskableTargetPosition
	2, // 1: world.TaskableTarget.waypoints:type_name -> world.TaskableTargetWaypoints
	3, // 2: world.TaskableTarget.entity:type_name -> world.TaskableTargetEntity
	7, // 3: world.TaskExecutionTarget.position:type_name -> world.PlanarPoint
	5, // 4: world.TaskExecutionTarget.waypoints:type_name -> world.TaskExecutionTargetWaypoints
	6, // 5: world.TaskExecutionTarget.entity:type_name -> world.TaskExecutionTargetEntity
	7, // 6: world.TaskExecutionTargetWaypoints.waypoint:type_name -> world.PlanarPoint
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tasking_proto_init() }
func file_tasking_proto_init() {
	if File_tasking_proto != nil {
		return
	}
	file_geometry_proto_init()
	file_tasking_proto_msgTypes[0].OneofWrappers = []any{}
	file_tasking_proto_msgTypes[2].OneofWrappers = []any{}
	file_tasking_proto_msgTypes[3].OneofWrappers = []any{}
	file_tasking_proto_msgTypes[4].OneofWrappers = []any{
		(*TaskExecutionTarget_Position)(nil),
		(*TaskExecutionTarget_Waypoints)(nil),
		(*TaskExecutionTarget_Entity)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasking_proto_rawDesc), len(file_tasking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tasking_proto_goTypes,
		DependencyIndexes: file_tasking_proto_depIdxs,
		MessageInfos:      file_tasking_proto_msgTypes,
	}.Build()
	File_tasking_proto = out.File
	file_tasking_proto_goTypes = nil
	file_tasking_proto_depIdxs = nil
}
