// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: taxonomy.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassificationTaxonomy struct {
	state      protoimpl.MessageState    `protogen:"open.v1"`
	Confidence *ClassificationConfidence `protobuf:"bytes,1,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ClassificationTaxonomy_Person
	//	*ClassificationTaxonomy_Animal
	//	*ClassificationTaxonomy_Infrastructure
	//	*ClassificationTaxonomy_Vehicle
	//	*ClassificationTaxonomy_Equipment
	//	*ClassificationTaxonomy_Emitter
	Kind          isClassificationTaxonomy_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationTaxonomy) Reset() {
	*x = ClassificationTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationTaxonomy) ProtoMessage() {}

func (x *ClassificationTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationTaxonomy.ProtoReflect.Descriptor instead.
func (*ClassificationTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{0}
}

func (x *ClassificationTaxonomy) GetConfidence() *ClassificationConfidence {
	if x != nil {
		return x.Confidence
	}
	return nil
}

func (x *ClassificationTaxonomy) GetKind() isClassificationTaxonomy_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ClassificationTaxonomy) GetPerson() *PersonTaxonomy {
	if x != nil {
		if x, ok := x.Kind.(*ClassificationTaxonomy_Person); ok {
			return x.Person
		}
	}
	return nil
}

func (x *ClassificationTaxonomy) GetAnimal() *AnimalTaxonomy {
	if x != nil {
		if x, ok := x.Kind.(*ClassificationTaxonomy_Animal); ok {
			return x.Animal
		}
	}
	return nil
}

func (x *ClassificationTaxonomy) GetInfrastructure() *InfrastructureTaxonomy {
	if x != nil {
		if x, ok := x.Kind.(*ClassificationTaxonomy_Infrastructure); ok {
			return x.Infrastructure
		}
	}
	return nil
}

func (x *ClassificationTaxonomy) GetVehicle() *VehicleTaxonomy {
	if x != nil {
		if x, ok := x.Kind.(*ClassificationTaxonomy_Vehicle); ok {
			return x.Vehicle
		}
	}
	return nil
}

func (x *ClassificationTaxonomy) GetEquipment() *EquipmentTaxonomy {
	if x != nil {
		if x, ok := x.Kind.(*ClassificationTaxonomy_Equipment); ok {
			return x.Equipment
		}
	}
	return nil
}

func (x *ClassificationTaxonomy) GetEmitter() *EmitterTaxonomy {
	if x != nil {
		if x, ok := x.Kind.(*ClassificationTaxonomy_Emitter); ok {
			return x.Emitter
		}
	}
	return nil
}

type isClassificationTaxonomy_Kind interface {
	isClassificationTaxonomy_Kind()
}

type ClassificationTaxonomy_Person struct {
	Person *PersonTaxonomy `protobuf:"bytes,10,opt,name=person,proto3,oneof"`
}

type ClassificationTaxonomy_Animal struct {
	Animal *AnimalTaxonomy `protobuf:"bytes,11,opt,name=animal,proto3,oneof"`
}

type ClassificationTaxonomy_Infrastructure struct {
	Infrastructure *InfrastructureTaxonomy `protobuf:"bytes,12,opt,name=infrastructure,proto3,oneof"`
}

type ClassificationTaxonomy_Vehicle struct {
	Vehicle *VehicleTaxonomy `protobuf:"bytes,13,opt,name=vehicle,proto3,oneof"`
}

type ClassificationTaxonomy_Equipment struct {
	Equipment *EquipmentTaxonomy `protobuf:"bytes,14,opt,name=equipment,proto3,oneof"`
}

type ClassificationTaxonomy_Emitter struct {
	Emitter *EmitterTaxonomy `protobuf:"bytes,15,opt,name=emitter,proto3,oneof"`
}

func (*ClassificationTaxonomy_Person) isClassificationTaxonomy_Kind() {}

func (*ClassificationTaxonomy_Animal) isClassificationTaxonomy_Kind() {}

func (*ClassificationTaxonomy_Infrastructure) isClassificationTaxonomy_Kind() {}

func (*ClassificationTaxonomy_Vehicle) isClassificationTaxonomy_Kind() {}

func (*ClassificationTaxonomy_Equipment) isClassificationTaxonomy_Kind() {}

func (*ClassificationTaxonomy_Emitter) isClassificationTaxonomy_Kind() {}

type ClassificationConfidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confidence    float32                `protobuf:"fixed32,1,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Pending       bool                   `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationConfidence) Reset() {
	*x = ClassificationConfidence{}
	mi := &file_taxonomy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationConfidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationConfidence) ProtoMessage() {}

func (x *ClassificationConfidence) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationConfidence.ProtoReflect.Descriptor instead.
func (*ClassificationConfidence) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{1}
}

func (x *ClassificationConfidence) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassificationConfidence) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

type PersonTaxonomy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonTaxonomy) Reset() {
	*x = PersonTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonTaxonomy) ProtoMessage() {}

func (x *PersonTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonTaxonomy.ProtoReflect.Descriptor instead.
func (*PersonTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{2}
}

type AnimalTaxonomy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AnimalTaxonomy_Air
	//	*AnimalTaxonomy_Land
	Kind          isAnimalTaxonomy_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimalTaxonomy) Reset() {
	*x = AnimalTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimalTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalTaxonomy) ProtoMessage() {}

func (x *AnimalTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalTaxonomy.ProtoReflect.Descriptor instead.
func (*AnimalTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{3}
}

func (x *AnimalTaxonomy) GetKind() isAnimalTaxonomy_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AnimalTaxonomy) GetAir() *AnimalTaxonomyAir {
	if x != nil {
		if x, ok := x.Kind.(*AnimalTaxonomy_Air); ok {
			return x.Air
		}
	}
	return nil
}

func (x *AnimalTaxonomy) GetLand() *AnimalTaxonomyLand {
	if x != nil {
		if x, ok := x.Kind.(*AnimalTaxonomy_Land); ok {
			return x.Land
		}
	}
	return nil
}

type isAnimalTaxonomy_Kind interface {
	isAnimalTaxonomy_Kind()
}

type AnimalTaxonomy_Air struct {
	Air *AnimalTaxonomyAir `protobuf:"bytes,1,opt,name=air,proto3,oneof"`
}

type AnimalTaxonomy_Land struct {
	Land *AnimalTaxonomyLand `protobuf:"bytes,2,opt,name=land,proto3,oneof"`
}

func (*AnimalTaxonomy_Air) isAnimalTaxonomy_Kind() {}

func (*AnimalTaxonomy_Land) isAnimalTaxonomy_Kind() {}

type AnimalTaxonomyBird struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimalTaxonomyBird) Reset() {
	*x = AnimalTaxonomyBird{}
	mi := &file_taxonomy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimalTaxonomyBird) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalTaxonomyBird) ProtoMessage() {}

func (x *AnimalTaxonomyBird) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalTaxonomyBird.ProtoReflect.Descriptor instead.
func (*AnimalTaxonomyBird) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{4}
}

type AnimalTaxonomyAir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bird          *AnimalTaxonomyBird    `protobuf:"bytes,1,opt,name=bird,proto3,oneof" json:"bird,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimalTaxonomyAir) Reset() {
	*x = AnimalTaxonomyAir{}
	mi := &file_taxonomy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimalTaxonomyAir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalTaxonomyAir) ProtoMessage() {}

func (x *AnimalTaxonomyAir) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalTaxonomyAir.ProtoReflect.Descriptor instead.
func (*AnimalTaxonomyAir) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{5}
}

func (x *AnimalTaxonomyAir) GetBird() *AnimalTaxonomyBird {
	if x != nil {
		return x.Bird
	}
	return nil
}

type AnimalTaxonomyHorse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimalTaxonomyHorse) Reset() {
	*x = AnimalTaxonomyHorse{}
	mi := &file_taxonomy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimalTaxonomyHorse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalTaxonomyHorse) ProtoMessage() {}

func (x *AnimalTaxonomyHorse) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalTaxonomyHorse.ProtoReflect.Descriptor instead.
func (*AnimalTaxonomyHorse) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{6}
}

type AnimalTaxonomyLand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Horse         *AnimalTaxonomyHorse   `protobuf:"bytes,1,opt,name=horse,proto3,oneof" json:"horse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimalTaxonomyLand) Reset() {
	*x = AnimalTaxonomyLand{}
	mi := &file_taxonomy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimalTaxonomyLand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalTaxonomyLand) ProtoMessage() {}

func (x *AnimalTaxonomyLand) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalTaxonomyLand.ProtoReflect.Descriptor instead.
func (*AnimalTaxonomyLand) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{7}
}

func (x *AnimalTaxonomyLand) GetHorse() *AnimalTaxonomyHorse {
	if x != nil {
		return x.Horse
	}
	return nil
}

type InfrastructureTaxonomy struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Tower         *InfrastructureTaxonomyTower  `protobuf:"bytes,1,opt,name=tower,proto3,oneof" json:"tower,omitempty"`
	Bridge        *InfrastructureTaxonomyBridge `protobuf:"bytes,2,opt,name=bridge,proto3,oneof" json:"bridge,omitempty"`
	Road          *InfrastructureTaxonomyRoad   `protobuf:"bytes,3,opt,name=road,proto3,oneof" json:"road,omitempty"`
	Dam           *InfrastructureTaxonomyDam    `protobuf:"bytes,4,opt,name=dam,proto3,oneof" json:"dam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureTaxonomy) Reset() {
	*x = InfrastructureTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureTaxonomy) ProtoMessage() {}

func (x *InfrastructureTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureTaxonomy.ProtoReflect.Descriptor instead.
func (*InfrastructureTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{8}
}

func (x *InfrastructureTaxonomy) GetTower() *InfrastructureTaxonomyTower {
	if x != nil {
		return x.Tower
	}
	return nil
}

func (x *InfrastructureTaxonomy) GetBridge() *InfrastructureTaxonomyBridge {
	if x != nil {
		return x.Bridge
	}
	return nil
}

func (x *InfrastructureTaxonomy) GetRoad() *InfrastructureTaxonomyRoad {
	if x != nil {
		return x.Road
	}
	return nil
}

func (x *InfrastructureTaxonomy) GetDam() *InfrastructureTaxonomyDam {
	if x != nil {
		return x.Dam
	}
	return nil
}

type InfrastructureTaxonomyTower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureTaxonomyTower) Reset() {
	*x = InfrastructureTaxonomyTower{}
	mi := &file_taxonomy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureTaxonomyTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureTaxonomyTower) ProtoMessage() {}

func (x *InfrastructureTaxonomyTower) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureTaxonomyTower.ProtoReflect.Descriptor instead.
func (*InfrastructureTaxonomyTower) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{9}
}

type InfrastructureTaxonomyBridge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureTaxonomyBridge) Reset() {
	*x = InfrastructureTaxonomyBridge{}
	mi := &file_taxonomy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureTaxonomyBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureTaxonomyBridge) ProtoMessage() {}

func (x *InfrastructureTaxonomyBridge) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureTaxonomyBridge.ProtoReflect.Descriptor instead.
func (*InfrastructureTaxonomyBridge) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{10}
}

type InfrastructureTaxonomyRoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureTaxonomyRoad) Reset() {
	*x = InfrastructureTaxonomyRoad{}
	mi := &file_taxonomy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureTaxonomyRoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureTaxonomyRoad) ProtoMessage() {}

func (x *InfrastructureTaxonomyRoad) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureTaxonomyRoad.ProtoReflect.Descriptor instead.
func (*InfrastructureTaxonomyRoad) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{11}
}

type InfrastructureTaxonomyDam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureTaxonomyDam) Reset() {
	*x = InfrastructureTaxonomyDam{}
	mi := &file_taxonomy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureTaxonomyDam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureTaxonomyDam) ProtoMessage() {}

func (x *InfrastructureTaxonomyDam) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureTaxonomyDam.ProtoReflect.Descriptor instead.
func (*InfrastructureTaxonomyDam) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{12}
}

type VehicleTaxonomyUnmanned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyUnmanned) Reset() {
	*x = VehicleTaxonomyUnmanned{}
	mi := &file_taxonomy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyUnmanned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyUnmanned) ProtoMessage() {}

func (x *VehicleTaxonomyUnmanned) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyUnmanned.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyUnmanned) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{13}
}

type VehicleTaxonomy struct {
	state    protoimpl.MessageState   `protogen:"open.v1"`
	Unmanned *VehicleTaxonomyUnmanned `protobuf:"bytes,1,opt,name=unmanned,proto3,oneof" json:"unmanned,omitempty"`
	// Types that are valid to be assigned to Domain:
	//
	//	*VehicleTaxonomy_Land
	//	*VehicleTaxonomy_Air
	//	*VehicleTaxonomy_Sea
	//	*VehicleTaxonomy_Subsurface
	Domain        isVehicleTaxonomy_Domain `protobuf_oneof:"domain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomy) Reset() {
	*x = VehicleTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomy) ProtoMessage() {}

func (x *VehicleTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomy.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{14}
}

func (x *VehicleTaxonomy) GetUnmanned() *VehicleTaxonomyUnmanned {
	if x != nil {
		return x.Unmanned
	}
	return nil
}

func (x *VehicleTaxonomy) GetDomain() isVehicleTaxonomy_Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *VehicleTaxonomy) GetLand() *VehicleTaxonomyLand {
	if x != nil {
		if x, ok := x.Domain.(*VehicleTaxonomy_Land); ok {
			return x.Land
		}
	}
	return nil
}

func (x *VehicleTaxonomy) GetAir() *VehicleTaxonomyAir {
	if x != nil {
		if x, ok := x.Domain.(*VehicleTaxonomy_Air); ok {
			return x.Air
		}
	}
	return nil
}

func (x *VehicleTaxonomy) GetSea() *VehicleTaxonomySea {
	if x != nil {
		if x, ok := x.Domain.(*VehicleTaxonomy_Sea); ok {
			return x.Sea
		}
	}
	return nil
}

func (x *VehicleTaxonomy) GetSubsurface() *VehicleTaxonomySubsurface {
	if x != nil {
		if x, ok := x.Domain.(*VehicleTaxonomy_Subsurface); ok {
			return x.Subsurface
		}
	}
	return nil
}

type isVehicleTaxonomy_Domain interface {
	isVehicleTaxonomy_Domain()
}

type VehicleTaxonomy_Land struct {
	Land *VehicleTaxonomyLand `protobuf:"bytes,10,opt,name=land,proto3,oneof"`
}

type VehicleTaxonomy_Air struct {
	Air *VehicleTaxonomyAir `protobuf:"bytes,11,opt,name=air,proto3,oneof"`
}

type VehicleTaxonomy_Sea struct {
	Sea *VehicleTaxonomySea `protobuf:"bytes,12,opt,name=sea,proto3,oneof"`
}

type VehicleTaxonomy_Subsurface struct {
	Subsurface *VehicleTaxonomySubsurface `protobuf:"bytes,13,opt,name=subsurface,proto3,oneof"`
}

func (*VehicleTaxonomy_Land) isVehicleTaxonomy_Domain() {}

func (*VehicleTaxonomy_Air) isVehicleTaxonomy_Domain() {}

func (*VehicleTaxonomy_Sea) isVehicleTaxonomy_Domain() {}

func (*VehicleTaxonomy_Subsurface) isVehicleTaxonomy_Domain() {}

type VehicleTaxonomyTracked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyTracked) Reset() {
	*x = VehicleTaxonomyTracked{}
	mi := &file_taxonomy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyTracked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyTracked) ProtoMessage() {}

func (x *VehicleTaxonomyTracked) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyTracked.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyTracked) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{15}
}

type VehicleTaxonomyTwoWheeled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyTwoWheeled) Reset() {
	*x = VehicleTaxonomyTwoWheeled{}
	mi := &file_taxonomy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyTwoWheeled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyTwoWheeled) ProtoMessage() {}

func (x *VehicleTaxonomyTwoWheeled) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyTwoWheeled.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyTwoWheeled) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{16}
}

type VehicleTaxonomyMultiWheeled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyMultiWheeled) Reset() {
	*x = VehicleTaxonomyMultiWheeled{}
	mi := &file_taxonomy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyMultiWheeled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyMultiWheeled) ProtoMessage() {}

func (x *VehicleTaxonomyMultiWheeled) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyMultiWheeled.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyMultiWheeled) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{17}
}

type VehicleTaxonomyLand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*VehicleTaxonomyLand_Tracked
	//	*VehicleTaxonomyLand_TwoWheeled
	//	*VehicleTaxonomyLand_MultiWheeled
	Kind          isVehicleTaxonomyLand_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyLand) Reset() {
	*x = VehicleTaxonomyLand{}
	mi := &file_taxonomy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyLand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyLand) ProtoMessage() {}

func (x *VehicleTaxonomyLand) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyLand.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyLand) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{18}
}

func (x *VehicleTaxonomyLand) GetKind() isVehicleTaxonomyLand_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *VehicleTaxonomyLand) GetTracked() *VehicleTaxonomyTracked {
	if x != nil {
		if x, ok := x.Kind.(*VehicleTaxonomyLand_Tracked); ok {
			return x.Tracked
		}
	}
	return nil
}

func (x *VehicleTaxonomyLand) GetTwoWheeled() *VehicleTaxonomyTwoWheeled {
	if x != nil {
		if x, ok := x.Kind.(*VehicleTaxonomyLand_TwoWheeled); ok {
			return x.TwoWheeled
		}
	}
	return nil
}

func (x *VehicleTaxonomyLand) GetMultiWheeled() *VehicleTaxonomyMultiWheeled {
	if x != nil {
		if x, ok := x.Kind.(*VehicleTaxonomyLand_MultiWheeled); ok {
			return x.MultiWheeled
		}
	}
	return nil
}

type isVehicleTaxonomyLand_Kind interface {
	isVehicleTaxonomyLand_Kind()
}

type VehicleTaxonomyLand_Tracked struct {
	Tracked *VehicleTaxonomyTracked `protobuf:"bytes,1,opt,name=tracked,proto3,oneof"`
}

type VehicleTaxonomyLand_TwoWheeled struct {
	TwoWheeled *VehicleTaxonomyTwoWheeled `protobuf:"bytes,2,opt,name=two_wheeled,json=twoWheeled,proto3,oneof"`
}

type VehicleTaxonomyLand_MultiWheeled struct {
	MultiWheeled *VehicleTaxonomyMultiWheeled `protobuf:"bytes,3,opt,name=multi_wheeled,json=multiWheeled,proto3,oneof"`
}

func (*VehicleTaxonomyLand_Tracked) isVehicleTaxonomyLand_Kind() {}

func (*VehicleTaxonomyLand_TwoWheeled) isVehicleTaxonomyLand_Kind() {}

func (*VehicleTaxonomyLand_MultiWheeled) isVehicleTaxonomyLand_Kind() {}

type VehicleTaxonomyAirRotary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyAirRotary) Reset() {
	*x = VehicleTaxonomyAirRotary{}
	mi := &file_taxonomy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyAirRotary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyAirRotary) ProtoMessage() {}

func (x *VehicleTaxonomyAirRotary) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyAirRotary.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyAirRotary) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{19}
}

type VehicleTaxonomyAirFixedWing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyAirFixedWing) Reset() {
	*x = VehicleTaxonomyAirFixedWing{}
	mi := &file_taxonomy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyAirFixedWing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyAirFixedWing) ProtoMessage() {}

func (x *VehicleTaxonomyAirFixedWing) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyAirFixedWing.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyAirFixedWing) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{20}
}

type VehicleTaxonomyAirLighterThanAir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyAirLighterThanAir) Reset() {
	*x = VehicleTaxonomyAirLighterThanAir{}
	mi := &file_taxonomy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyAirLighterThanAir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyAirLighterThanAir) ProtoMessage() {}

func (x *VehicleTaxonomyAirLighterThanAir) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyAirLighterThanAir.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyAirLighterThanAir) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{21}
}

type VehicleTaxonomyAir struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*VehicleTaxonomyAir_FixedWing
	//	*VehicleTaxonomyAir_LighterThanAir
	//	*VehicleTaxonomyAir_Rotary
	Kind          isVehicleTaxonomyAir_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomyAir) Reset() {
	*x = VehicleTaxonomyAir{}
	mi := &file_taxonomy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomyAir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomyAir) ProtoMessage() {}

func (x *VehicleTaxonomyAir) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomyAir.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomyAir) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{22}
}

func (x *VehicleTaxonomyAir) GetKind() isVehicleTaxonomyAir_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *VehicleTaxonomyAir) GetFixedWing() *VehicleTaxonomyAirFixedWing {
	if x != nil {
		if x, ok := x.Kind.(*VehicleTaxonomyAir_FixedWing); ok {
			return x.FixedWing
		}
	}
	return nil
}

func (x *VehicleTaxonomyAir) GetLighterThanAir() *VehicleTaxonomyAirLighterThanAir {
	if x != nil {
		if x, ok := x.Kind.(*VehicleTaxonomyAir_LighterThanAir); ok {
			return x.LighterThanAir
		}
	}
	return nil
}

func (x *VehicleTaxonomyAir) GetRotary() *VehicleTaxonomyAirRotary {
	if x != nil {
		if x, ok := x.Kind.(*VehicleTaxonomyAir_Rotary); ok {
			return x.Rotary
		}
	}
	return nil
}

type isVehicleTaxonomyAir_Kind interface {
	isVehicleTaxonomyAir_Kind()
}

type VehicleTaxonomyAir_FixedWing struct {
	FixedWing *VehicleTaxonomyAirFixedWing `protobuf:"bytes,1,opt,name=fixed_wing,json=fixedWing,proto3,oneof"`
}

type VehicleTaxonomyAir_LighterThanAir struct {
	LighterThanAir *VehicleTaxonomyAirLighterThanAir `protobuf:"bytes,2,opt,name=lighter_than_air,json=lighterThanAir,proto3,oneof"`
}

type VehicleTaxonomyAir_Rotary struct {
	Rotary *VehicleTaxonomyAirRotary `protobuf:"bytes,3,opt,name=rotary,proto3,oneof"`
}

func (*VehicleTaxonomyAir_FixedWing) isVehicleTaxonomyAir_Kind() {}

func (*VehicleTaxonomyAir_LighterThanAir) isVehicleTaxonomyAir_Kind() {}

func (*VehicleTaxonomyAir_Rotary) isVehicleTaxonomyAir_Kind() {}

type VehicleTaxonomySea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomySea) Reset() {
	*x = VehicleTaxonomySea{}
	mi := &file_taxonomy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomySea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomySea) ProtoMessage() {}

func (x *VehicleTaxonomySea) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomySea.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomySea) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{23}
}

type VehicleTaxonomySubsurface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTaxonomySubsurface) Reset() {
	*x = VehicleTaxonomySubsurface{}
	mi := &file_taxonomy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTaxonomySubsurface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTaxonomySubsurface) ProtoMessage() {}

func (x *VehicleTaxonomySubsurface) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTaxonomySubsurface.ProtoReflect.Descriptor instead.
func (*VehicleTaxonomySubsurface) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{24}
}

type EquipmentTaxonomySensorRadar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensorRadar) Reset() {
	*x = EquipmentTaxonomySensorRadar{}
	mi := &file_taxonomy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensorRadar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensorRadar) ProtoMessage() {}

func (x *EquipmentTaxonomySensorRadar) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensorRadar.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensorRadar) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{25}
}

type EquipmentTaxonomySensorEW struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensorEW) Reset() {
	*x = EquipmentTaxonomySensorEW{}
	mi := &file_taxonomy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensorEW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensorEW) ProtoMessage() {}

func (x *EquipmentTaxonomySensorEW) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensorEW.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensorEW) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{26}
}

type EquipmentTaxonomySensorCBRN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensorCBRN) Reset() {
	*x = EquipmentTaxonomySensorCBRN{}
	mi := &file_taxonomy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensorCBRN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensorCBRN) ProtoMessage() {}

func (x *EquipmentTaxonomySensorCBRN) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensorCBRN.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensorCBRN) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{27}
}

type EquipmentTaxonomySensorAcoustic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensorAcoustic) Reset() {
	*x = EquipmentTaxonomySensorAcoustic{}
	mi := &file_taxonomy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensorAcoustic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensorAcoustic) ProtoMessage() {}

func (x *EquipmentTaxonomySensorAcoustic) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensorAcoustic.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensorAcoustic) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{28}
}

type EquipmentTaxonomySensorElectroOptical struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensorElectroOptical) Reset() {
	*x = EquipmentTaxonomySensorElectroOptical{}
	mi := &file_taxonomy_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensorElectroOptical) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensorElectroOptical) ProtoMessage() {}

func (x *EquipmentTaxonomySensorElectroOptical) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensorElectroOptical.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensorElectroOptical) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{29}
}

type EquipmentTaxonomySensorEmplaced struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensorEmplaced) Reset() {
	*x = EquipmentTaxonomySensorEmplaced{}
	mi := &file_taxonomy_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensorEmplaced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensorEmplaced) ProtoMessage() {}

func (x *EquipmentTaxonomySensorEmplaced) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensorEmplaced.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensorEmplaced) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{30}
}

type EquipmentTaxonomySensor struct {
	state    protoimpl.MessageState           `protogen:"open.v1"`
	Emplaced *EquipmentTaxonomySensorEmplaced `protobuf:"bytes,1,opt,name=emplaced,proto3,oneof" json:"emplaced,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*EquipmentTaxonomySensor_Radar
	//	*EquipmentTaxonomySensor_Ew
	//	*EquipmentTaxonomySensor_Cbrn
	//	*EquipmentTaxonomySensor_Acoustic
	//	*EquipmentTaxonomySensor_ElectroOptical
	Kind          isEquipmentTaxonomySensor_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomySensor) Reset() {
	*x = EquipmentTaxonomySensor{}
	mi := &file_taxonomy_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomySensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomySensor) ProtoMessage() {}

func (x *EquipmentTaxonomySensor) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomySensor.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomySensor) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{31}
}

func (x *EquipmentTaxonomySensor) GetEmplaced() *EquipmentTaxonomySensorEmplaced {
	if x != nil {
		return x.Emplaced
	}
	return nil
}

func (x *EquipmentTaxonomySensor) GetKind() isEquipmentTaxonomySensor_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *EquipmentTaxonomySensor) GetRadar() *EquipmentTaxonomySensorRadar {
	if x != nil {
		if x, ok := x.Kind.(*EquipmentTaxonomySensor_Radar); ok {
			return x.Radar
		}
	}
	return nil
}

func (x *EquipmentTaxonomySensor) GetEw() *EquipmentTaxonomySensorEW {
	if x != nil {
		if x, ok := x.Kind.(*EquipmentTaxonomySensor_Ew); ok {
			return x.Ew
		}
	}
	return nil
}

func (x *EquipmentTaxonomySensor) GetCbrn() *EquipmentTaxonomySensorCBRN {
	if x != nil {
		if x, ok := x.Kind.(*EquipmentTaxonomySensor_Cbrn); ok {
			return x.Cbrn
		}
	}
	return nil
}

func (x *EquipmentTaxonomySensor) GetAcoustic() *EquipmentTaxonomySensorAcoustic {
	if x != nil {
		if x, ok := x.Kind.(*EquipmentTaxonomySensor_Acoustic); ok {
			return x.Acoustic
		}
	}
	return nil
}

func (x *EquipmentTaxonomySensor) GetElectroOptical() *EquipmentTaxonomySensorElectroOptical {
	if x != nil {
		if x, ok := x.Kind.(*EquipmentTaxonomySensor_ElectroOptical); ok {
			return x.ElectroOptical
		}
	}
	return nil
}

type isEquipmentTaxonomySensor_Kind interface {
	isEquipmentTaxonomySensor_Kind()
}

type EquipmentTaxonomySensor_Radar struct {
	Radar *EquipmentTaxonomySensorRadar `protobuf:"bytes,10,opt,name=radar,proto3,oneof"`
}

type EquipmentTaxonomySensor_Ew struct {
	Ew *EquipmentTaxonomySensorEW `protobuf:"bytes,11,opt,name=ew,proto3,oneof"`
}

type EquipmentTaxonomySensor_Cbrn struct {
	Cbrn *EquipmentTaxonomySensorCBRN `protobuf:"bytes,12,opt,name=cbrn,proto3,oneof"`
}

type EquipmentTaxonomySensor_Acoustic struct {
	Acoustic *EquipmentTaxonomySensorAcoustic `protobuf:"bytes,13,opt,name=acoustic,proto3,oneof"`
}

type EquipmentTaxonomySensor_ElectroOptical struct {
	ElectroOptical *EquipmentTaxonomySensorElectroOptical `protobuf:"bytes,14,opt,name=electro_optical,json=electroOptical,proto3,oneof"`
}

func (*EquipmentTaxonomySensor_Radar) isEquipmentTaxonomySensor_Kind() {}

func (*EquipmentTaxonomySensor_Ew) isEquipmentTaxonomySensor_Kind() {}

func (*EquipmentTaxonomySensor_Cbrn) isEquipmentTaxonomySensor_Kind() {}

func (*EquipmentTaxonomySensor_Acoustic) isEquipmentTaxonomySensor_Kind() {}

func (*EquipmentTaxonomySensor_ElectroOptical) isEquipmentTaxonomySensor_Kind() {}

type EquipmentTaxonomy struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Sensor        *EquipmentTaxonomySensor `protobuf:"bytes,1,opt,name=sensor,proto3,oneof" json:"sensor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentTaxonomy) Reset() {
	*x = EquipmentTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentTaxonomy) ProtoMessage() {}

func (x *EquipmentTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentTaxonomy.ProtoReflect.Descriptor instead.
func (*EquipmentTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{32}
}

func (x *EquipmentTaxonomy) GetSensor() *EquipmentTaxonomySensor {
	if x != nil {
		return x.Sensor
	}
	return nil
}

type EmitterTaxonomy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitterTaxonomy) Reset() {
	*x = EmitterTaxonomy{}
	mi := &file_taxonomy_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitterTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitterTaxonomy) ProtoMessage() {}

func (x *EmitterTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_taxonomy_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitterTaxonomy.ProtoReflect.Descriptor instead.
func (*EmitterTaxonomy) Descriptor() ([]byte, []int) {
	return file_taxonomy_proto_rawDescGZIP(), []int{33}
}

var File_taxonomy_proto protoreflect.FileDescriptor

const file_taxonomy_proto_rawDesc = "" +
	"\n" +
	"\x0etaxonomy.proto\x12\x05world\"\xae\x03\n" +
	"\x16ClassificationTaxonomy\x12?\n" +
	"\n" +
	"confidence\x18\x01 \x01(\v2\x1f.world.ClassificationConfidenceR\n" +
	"confidence\x12/\n" +
	"\x06person\x18\n" +
	" \x01(\v2\x15.world.PersonTaxonomyH\x00R\x06person\x12/\n" +
	"\x06animal\x18\v \x01(\v2\x15.world.AnimalTaxonomyH\x00R\x06animal\x12G\n" +
	"\x0einfrastructure\x18\f \x01(\v2\x1d.world.InfrastructureTaxonomyH\x00R\x0einfrastructure\x122\n" +
	"\avehicle\x18\r \x01(\v2\x16.world.VehicleTaxonomyH\x00R\avehicle\x128\n" +
	"\tequipment\x18\x0e \x01(\v2\x18.world.EquipmentTaxonomyH\x00R\tequipment\x122\n" +
	"\aemitter\x18\x0f \x01(\v2\x16.world.EmitterTaxonomyH\x00R\aemitterB\x06\n" +
	"\x04kind\"T\n" +
	"\x18ClassificationConfidence\x12\x1e\n" +
	"\n" +
	"confidence\x18\x01 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\apending\x18\x02 \x01(\bR\apending\"\x10\n" +
	"\x0ePersonTaxonomy\"w\n" +
	"\x0eAnimalTaxonomy\x12,\n" +
	"\x03air\x18\x01 \x01(\v2\x18.world.AnimalTaxonomyAirH\x00R\x03air\x12/\n" +
	"\x04land\x18\x02 \x01(\v2\x19.world.AnimalTaxonomyLandH\x00R\x04landB\x06\n" +
	"\x04kind\"\x14\n" +
	"\x12AnimalTaxonomyBird\"P\n" +
	"\x11AnimalTaxonomyAir\x122\n" +
	"\x04bird\x18\x01 \x01(\v2\x19.world.AnimalTaxonomyBirdH\x00R\x04bird\x88\x01\x01B\a\n" +
	"\x05_bird\"\x15\n" +
	"\x13AnimalTaxonomyHorse\"U\n" +
	"\x12AnimalTaxonomyLand\x125\n" +
	"\x05horse\x18\x01 \x01(\v2\x1a.world.AnimalTaxonomyHorseH\x00R\x05horse\x88\x01\x01B\b\n" +
	"\x06_horse\"\xb4\x02\n" +
	"\x16InfrastructureTaxonomy\x12=\n" +
	"\x05tower\x18\x01 \x01(\v2\".world.InfrastructureTaxonomyTowerH\x00R\x05tower\x88\x01\x01\x12@\n" +
	"\x06bridge\x18\x02 \x01(\v2#.world.InfrastructureTaxonomyBridgeH\x01R\x06bridge\x88\x01\x01\x12:\n" +
	"\x04road\x18\x03 \x01(\v2!.world.InfrastructureTaxonomyRoadH\x02R\x04road\x88\x01\x01\x127\n" +
	"\x03dam\x18\x04 \x01(\v2 .world.InfrastructureTaxonomyDamH\x03R\x03dam\x88\x01\x01B\b\n" +
	"\x06_towerB\t\n" +
	"\a_bridgeB\a\n" +
	"\x05_roadB\x06\n" +
	"\x04_dam\"\x1d\n" +
	"\x1bInfrastructureTaxonomyTower\"\x1e\n" +
	"\x1cInfrastructureTaxonomyBridge\"\x1c\n" +
	"\x1aInfrastructureTaxonomyRoad\"\x1b\n" +
	"\x19InfrastructureTaxonomyDam\"\x19\n" +
	"\x17VehicleTaxonomyUnmanned\"\xbd\x02\n" +
	"\x0fVehicleTaxonomy\x12?\n" +
	"\bunmanned\x18\x01 \x01(\v2\x1e.world.VehicleTaxonomyUnmannedH\x01R\bunmanned\x88\x01\x01\x120\n" +
	"\x04land\x18\n" +
	" \x01(\v2\x1a.world.VehicleTaxonomyLandH\x00R\x04land\x12-\n" +
	"\x03air\x18\v \x01(\v2\x19.world.VehicleTaxonomyAirH\x00R\x03air\x12-\n" +
	"\x03sea\x18\f \x01(\v2\x19.world.VehicleTaxonomySeaH\x00R\x03sea\x12B\n" +
	"\n" +
	"subsurface\x18\r \x01(\v2 .world.VehicleTaxonomySubsurfaceH\x00R\n" +
	"subsurfaceB\b\n" +
	"\x06domainB\v\n" +
	"\t_unmanned\"\x18\n" +
	"\x16VehicleTaxonomyTracked\"\x1b\n" +
	"\x19VehicleTaxonomyTwoWheeled\"\x1d\n" +
	"\x1bVehicleTaxonomyMultiWheeled\"\xe8\x01\n" +
	"\x13VehicleTaxonomyLand\x129\n" +
	"\atracked\x18\x01 \x01(\v2\x1d.world.VehicleTaxonomyTrackedH\x00R\atracked\x12C\n" +
	"\vtwo_wheeled\x18\x02 \x01(\v2 .world.VehicleTaxonomyTwoWheeledH\x00R\n" +
	"twoWheeled\x12I\n" +
	"\rmulti_wheeled\x18\x03 \x01(\v2\".world.VehicleTaxonomyMultiWheeledH\x00R\fmultiWheeledB\x06\n" +
	"\x04kind\"\x1a\n" +
	"\x18VehicleTaxonomyAirRotary\"\x1d\n" +
	"\x1bVehicleTaxonomyAirFixedWing\"\"\n" +
	" VehicleTaxonomyAirLighterThanAir\"\xf1\x01\n" +
	"\x12VehicleTaxonomyAir\x12C\n" +
	"\n" +
	"fixed_wing\x18\x01 \x01(\v2\".world.VehicleTaxonomyAirFixedWingH\x00R\tfixedWing\x12S\n" +
	"\x10lighter_than_air\x18\x02 \x01(\v2'.world.VehicleTaxonomyAirLighterThanAirH\x00R\x0elighterThanAir\x129\n" +
	"\x06rotary\x18\x03 \x01(\v2\x1f.world.VehicleTaxonomyAirRotaryH\x00R\x06rotaryB\x06\n" +
	"\x04kind\"\x14\n" +
	"\x12VehicleTaxonomySea\"\x1b\n" +
	"\x19VehicleTaxonomySubsurface\"\x1e\n" +
	"\x1cEquipmentTaxonomySensorRadar\"\x1b\n" +
	"\x19EquipmentTaxonomySensorEW\"\x1d\n" +
	"\x1bEquipmentTaxonomySensorCBRN\"!\n" +
	"\x1fEquipmentTaxonomySensorAcoustic\"'\n" +
	"%EquipmentTaxonomySensorElectroOptical\"!\n" +
	"\x1fEquipmentTaxonomySensorEmplaced\"\xc1\x03\n" +
	"\x17EquipmentTaxonomySensor\x12G\n" +
	"\bemplaced\x18\x01 \x01(\v2&.world.EquipmentTaxonomySensorEmplacedH\x01R\bemplaced\x88\x01\x01\x12;\n" +
	"\x05radar\x18\n" +
	" \x01(\v2#.world.EquipmentTaxonomySensorRadarH\x00R\x05radar\x122\n" +
	"\x02ew\x18\v \x01(\v2 .world.EquipmentTaxonomySensorEWH\x00R\x02ew\x128\n" +
	"\x04cbrn\x18\f \x01(\v2\".world.EquipmentTaxonomySensorCBRNH\x00R\x04cbrn\x12D\n" +
	"\bacoustic\x18\r \x01(\v2&.world.EquipmentTaxonomySensorAcousticH\x00R\bacoustic\x12W\n" +
	"\x0felectro_optical\x18\x0e \x01(\v2,.world.EquipmentTaxonomySensorElectroOpticalH\x00R\x0eelectroOpticalB\x06\n" +
	"\x04kindB\v\n" +
	"\t_emplaced\"[\n" +
	"\x11EquipmentTaxonomy\x12;\n" +
	"\x06sensor\x18\x01 \x01(\v2\x1e.world.EquipmentTaxonomySensorH\x00R\x06sensor\x88\x01\x01B\t\n" +
	"\a_sensor\"\x11\n" +
	"\x0fEmitterTaxonomyB Z\x1egithub.com/projectqai/proto/gob\x06proto3"

var (
	file_taxonomy_proto_rawDescOnce sync.Once
	file_taxonomy_proto_rawDescData []byte
)

func file_taxonomy_proto_rawDescGZIP() []byte {
	file_taxonomy_proto_rawDescOnce.Do(func() {
		file_taxonomy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taxonomy_proto_rawDesc), len(file_taxonomy_proto_rawDesc)))
	})
	return file_taxonomy_proto_rawDescData
}

var file_taxonomy_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_taxonomy_proto_goTypes = []any{
	(*ClassificationTaxonomy)(nil),                // 0: world.ClassificationTaxonomy
	(*ClassificationConfidence)(nil),              // 1: world.ClassificationConfidence
	(*PersonTaxonomy)(nil),                        // 2: world.PersonTaxonomy
	(*AnimalTaxonomy)(nil),                        // 3: world.AnimalTaxonomy
	(*AnimalTaxonomyBird)(nil),                    // 4: world.AnimalTaxonomyBird
	(*AnimalTaxonomyAir)(nil),                     // 5: world.AnimalTaxonomyAir
	(*AnimalTaxonomyHorse)(nil),                   // 6: world.AnimalTaxonomyHorse
	(*AnimalTaxonomyLand)(nil),                    // 7: world.AnimalTaxonomyLand
	(*InfrastructureTaxonomy)(nil),                // 8: world.InfrastructureTaxonomy
	(*InfrastructureTaxonomyTower)(nil),           // 9: world.InfrastructureTaxonomyTower
	(*InfrastructureTaxonomyBridge)(nil),          // 10: world.InfrastructureTaxonomyBridge
	(*InfrastructureTaxonomyRoad)(nil),            // 11: world.InfrastructureTaxonomyRoad
	(*InfrastructureTaxonomyDam)(nil),             // 12: world.InfrastructureTaxonomyDam
	(*VehicleTaxonomyUnmanned)(nil),               // 13: world.VehicleTaxonomyUnmanned
	(*VehicleTaxonomy)(nil),                       // 14: world.VehicleTaxonomy
	(*VehicleTaxonomyTracked)(nil),                // 15: world.VehicleTaxonomyTracked
	(*VehicleTaxonomyTwoWheeled)(nil),             // 16: world.VehicleTaxonomyTwoWheeled
	(*VehicleTaxonomyMultiWheeled)(nil),           // 17: world.VehicleTaxonomyMultiWheeled
	(*VehicleTaxonomyLand)(nil),                   // 18: world.VehicleTaxonomyLand
	(*VehicleTaxonomyAirRotary)(nil),              // 19: world.VehicleTaxonomyAirRotary
	(*VehicleTaxonomyAirFixedWing)(nil),           // 20: world.VehicleTaxonomyAirFixedWing
	(*VehicleTaxonomyAirLighterThanAir)(nil),      // 21: world.VehicleTaxonomyAirLighterThanAir
	(*VehicleTaxonomyAir)(nil),                    // 22: world.VehicleTaxonomyAir
	(*VehicleTaxonomySea)(nil),                    // 23: world.VehicleTaxonomySea
	(*VehicleTaxonomySubsurface)(nil),             // 24: world.VehicleTaxonomySubsurface
	(*EquipmentTaxonomySensorRadar)(nil),          // 25: world.EquipmentTaxonomySensorRadar
	(*EquipmentTaxonomySensorEW)(nil),             // 26: world.EquipmentTaxonomySensorEW
	(*EquipmentTaxonomySensorCBRN)(nil),           // 27: world.EquipmentTaxonomySensorCBRN
	(*EquipmentTaxonomySensorAcoustic)(nil),       // 28: world.EquipmentTaxonomySensorAcoustic
	(*EquipmentTaxonomySensorElectroOptical)(nil), // 29: world.EquipmentTaxonomySensorElectroOptical
	(*EquipmentTaxonomySensorEmplaced)(nil),       // 30: world.EquipmentTaxonomySensorEmplaced
	(*EquipmentTaxonomySensor)(nil),               // 31: world.EquipmentTaxonomySensor
	(*EquipmentTaxonomy)(nil),                     // 32: world.EquipmentTaxonomy
	(*EmitterTaxonomy)(nil),                       // 33: world.EmitterTaxonomy
}
var file_taxonomy_proto_depIdxs = []int32{
	1,  // 0: world.ClassificationTaxonomy.confidence:type_name -> world.ClassificationConfidence
	2,  // 1: world.ClassificationTaxonomy.person:type_name -> world.PersonTaxonomy
	3,  // 2: world.ClassificationTaxonomy.animal:type_name -> world.AnimalTaxonomy
	8,  // 3: world.ClassificationTaxonomy.infrastructure:type_name -> world.InfrastructureTaxonomy
	14, // 4: world.ClassificationTaxonomy.vehicle:type_name -> world.VehicleTaxonomy
	32, // 5: world.ClassificationTaxonomy.equipment:type_name -> world.EquipmentTaxonomy
	33, // 6: world.ClassificationTaxonomy.emitter:type_name -> world.EmitterTaxonomy
	5,  // 7: world.AnimalTaxonomy.air:type_name -> world.AnimalTaxonomyAir
	7,  // 8: world.AnimalTaxonomy.land:type_name -> world.AnimalTaxonomyLand
	4,  // 9: world.AnimalTaxonomyAir.bird:type_name -> world.AnimalTaxonomyBird
	6,  // 10: world.AnimalTaxonomyLand.horse:type_name -> world.AnimalTaxonomyHorse
	9,  // 11: world.InfrastructureTaxonomy.tower:type_name -> world.InfrastructureTaxonomyTower
	10, // 12: world.InfrastructureTaxonomy.bridge:type_name -> world.InfrastructureTaxonomyBridge
	11, // 13: world.InfrastructureTaxonomy.road:type_name -> world.InfrastructureTaxonomyRoad
	12, // 14: world.InfrastructureTaxonomy.dam:type_name -> world.InfrastructureTaxonomyDam
	13, // 15: world.VehicleTaxonomy.unmanned:type_name -> world.VehicleTaxonomyUnmanned
	18, // 16: world.VehicleTaxonomy.land:type_name -> world.VehicleTaxonomyLand
	22, // 17: world.VehicleTaxonomy.air:type_name -> world.VehicleTaxonomyAir
	23, // 18: world.VehicleTaxonomy.sea:type_name -> world.VehicleTaxonomySea
	24, // 19: world.VehicleTaxonomy.subsurface:type_name -> world.VehicleTaxonomySubsurface
	15, // 20: world.VehicleTaxonomyLand.tracked:type_name -> world.VehicleTaxonomyTracked
	16, // 21: world.VehicleTaxonomyLand.two_wheeled:type_name -> world.VehicleTaxonomyTwoWheeled
	17, // 22: world.VehicleTaxonomyLand.multi_wheeled:type_name -> world.VehicleTaxonomyMultiWheeled
	20, // 23: world.VehicleTaxonomyAir.fixed_wing:type_name -> world.VehicleTaxonomyAirFixedWing
	21, // 24: world.VehicleTaxonomyAir.lighter_than_air:type_name -> world.VehicleTaxonomyAirLighterThanAir
	19, // 25: world.VehicleTaxonomyAir.rotary:type_name -> world.VehicleTaxonomyAirRotary
	30, // 26: world.EquipmentTaxonomySensor.emplaced:type_name -> world.EquipmentTaxonomySensorEmplaced
	25, // 27: world.EquipmentTaxonomySensor.radar:type_name -> world.EquipmentTaxonomySensorRadar
	26, // 28: world.EquipmentTaxonomySensor.ew:type_name -> world.EquipmentTaxonomySensorEW
	27, // 29: world.EquipmentTaxonomySensor.cbrn:type_name -> world.EquipmentTaxonomySensorCBRN
	28, // 30: world.EquipmentTaxonomySensor.acoustic:type_name -> world.EquipmentTaxonomySensorAcoustic
	29, // 31: world.EquipmentTaxonomySensor.electro_optical:type_name -> world.EquipmentTaxonomySensorElectroOptical
	31, // 32: world.EquipmentTaxonomy.sensor:type_name -> world.EquipmentTaxonomySensor
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_taxonomy_proto_init() }
func file_taxonomy_proto_init() {
	if File_taxonomy_proto != nil {
		return
	}
	file_taxonomy_proto_msgTypes[0].OneofWrappers = []any{
		(*ClassificationTaxonomy_Person)(nil),
		(*ClassificationTaxonomy_Animal)(nil),
		(*ClassificationTaxonomy_Infrastructure)(nil),
		(*ClassificationTaxonomy_Vehicle)(nil),
		(*ClassificationTaxonomy_Equipment)(nil),
		(*ClassificationTaxonomy_Emitter)(nil),
	}
	file_taxonomy_proto_msgTypes[3].OneofWrappers = []any{
		(*AnimalTaxonomy_Air)(nil),
		(*AnimalTaxonomy_Land)(nil),
	}
	file_taxonomy_proto_msgTypes[5].OneofWrappers = []any{}
	file_taxonomy_proto_msgTypes[7].OneofWrappers = []any{}
	file_taxonomy_proto_msgTypes[8].OneofWrappers = []any{}
	file_taxonomy_proto_msgTypes[14].OneofWrappers = []any{
		(*VehicleTaxonomy_Land)(nil),
		(*VehicleTaxonomy_Air)(nil),
		(*VehicleTaxonomy_Sea)(nil),
		(*VehicleTaxonomy_Subsurface)(nil),
	}
	file_taxonomy_proto_msgTypes[18].OneofWrappers = []any{
		(*VehicleTaxonomyLand_Tracked)(nil),
		(*VehicleTaxonomyLand_TwoWheeled)(nil),
		(*VehicleTaxonomyLand_MultiWheeled)(nil),
	}
	file_taxonomy_proto_msgTypes[22].OneofWrappers = []any{
		(*VehicleTaxonomyAir_FixedWing)(nil),
		(*VehicleTaxonomyAir_LighterThanAir)(nil),
		(*VehicleTaxonomyAir_Rotary)(nil),
	}
	file_taxonomy_proto_msgTypes[31].OneofWrappers = []any{
		(*EquipmentTaxonomySensor_Radar)(nil),
		(*EquipmentTaxonomySensor_Ew)(nil),
		(*EquipmentTaxonomySensor_Cbrn)(nil),
		(*EquipmentTaxonomySensor_Acoustic)(nil),
		(*EquipmentTaxonomySensor_ElectroOptical)(nil),
	}
	file_taxonomy_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taxonomy_proto_rawDesc), len(file_taxonomy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taxonomy_proto_goTypes,
		DependencyIndexes: file_taxonomy_proto_depIdxs,
		MessageInfos:      file_taxonomy_proto_msgTypes,
	}.Build()
	File_taxonomy_proto = out.File
	file_taxonomy_proto_goTypes = nil
	file_taxonomy_proto_depIdxs = nil
}
