// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: timeline.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimelineService_MoveTimeline_FullMethodName = "/timeline.TimelineService/MoveTimeline"
	TimelineService_GetTimeline_FullMethodName  = "/timeline.TimelineService/GetTimeline"
)

// TimelineServiceClient is the client API for TimelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimelineServiceClient interface {
	MoveTimeline(ctx context.Context, in *MoveTimelineRequest, opts ...grpc.CallOption) (*MoveTimelineResponse, error)
	GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTimelineResponse], error)
}

type timelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimelineServiceClient(cc grpc.ClientConnInterface) TimelineServiceClient {
	return &timelineServiceClient{cc}
}

func (c *timelineServiceClient) MoveTimeline(ctx context.Context, in *MoveTimelineRequest, opts ...grpc.CallOption) (*MoveTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveTimelineResponse)
	err := c.cc.Invoke(ctx, TimelineService_MoveTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTimelineResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TimelineService_ServiceDesc.Streams[0], TimelineService_GetTimeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTimelineRequest, GetTimelineResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TimelineService_GetTimelineClient = grpc.ServerStreamingClient[GetTimelineResponse]

// TimelineServiceServer is the server API for TimelineService service.
// All implementations must embed UnimplementedTimelineServiceServer
// for forward compatibility.
type TimelineServiceServer interface {
	MoveTimeline(context.Context, *MoveTimelineRequest) (*MoveTimelineResponse, error)
	GetTimeline(*GetTimelineRequest, grpc.ServerStreamingServer[GetTimelineResponse]) error
	mustEmbedUnimplementedTimelineServiceServer()
}

// UnimplementedTimelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimelineServiceServer struct{}

func (UnimplementedTimelineServiceServer) MoveTimeline(context.Context, *MoveTimelineRequest) (*MoveTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) GetTimeline(*GetTimelineRequest, grpc.ServerStreamingServer[GetTimelineResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) mustEmbedUnimplementedTimelineServiceServer() {}
func (UnimplementedTimelineServiceServer) testEmbeddedByValue()                         {}

// UnsafeTimelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimelineServiceServer will
// result in compilation errors.
type UnsafeTimelineServiceServer interface {
	mustEmbedUnimplementedTimelineServiceServer()
}

func RegisterTimelineServiceServer(s grpc.ServiceRegistrar, srv TimelineServiceServer) {
	// If the following call panics, it indicates UnimplementedTimelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimelineService_ServiceDesc, srv)
}

func _TimelineService_MoveTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).MoveTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_MoveTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).MoveTimeline(ctx, req.(*MoveTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetTimeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTimelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimelineServiceServer).GetTimeline(m, &grpc.GenericServerStream[GetTimelineRequest, GetTimelineResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TimelineService_GetTimelineServer = grpc.ServerStreamingServer[GetTimelineResponse]

// TimelineService_ServiceDesc is the grpc.ServiceDesc for TimelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timeline.TimelineService",
	HandlerType: (*TimelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MoveTimeline",
			Handler:    _TimelineService_MoveTimeline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTimeline",
			Handler:       _TimelineService_GetTimeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "timeline.proto",
}
