// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: world.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityChange int32

const (
	EntityChange_Invalid    EntityChange = 0
	EntityChange_Updated    EntityChange = 1
	EntityChange_Expired    EntityChange = 2
	EntityChange_Unobserved EntityChange = 3
)

// Enum value maps for EntityChange.
var (
	EntityChange_name = map[int32]string{
		0: "Invalid",
		1: "Updated",
		2: "Expired",
		3: "Unobserved",
	}
	EntityChange_value = map[string]int32{
		"Invalid":    0,
		"Updated":    1,
		"Expired":    2,
		"Unobserved": 3,
	}
)

func (x EntityChange) Enum() *EntityChange {
	p := new(EntityChange)
	*p = x
	return p
}

func (x EntityChange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityChange) Descriptor() protoreflect.EnumDescriptor {
	return file_world_proto_enumTypes[0].Descriptor()
}

func (EntityChange) Type() protoreflect.EnumType {
	return &file_world_proto_enumTypes[0]
}

func (x EntityChange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityChange.Descriptor instead.
func (EntityChange) EnumDescriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

type Entity struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	Id                  string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Controller          *ControllerRef                `protobuf:"bytes,3,opt,name=controller,proto3,oneof" json:"controller,omitempty"`
	Lifetime            *Lifetime                     `protobuf:"bytes,4,opt,name=lifetime,proto3,oneof" json:"lifetime,omitempty"`
	Geo                 *GeoSpatialComponent          `protobuf:"bytes,11,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	Symbol              *SymbolComponent              `protobuf:"bytes,12,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Camera              *CameraComponent              `protobuf:"bytes,15,opt,name=camera,proto3,oneof" json:"camera,omitempty"`
	Detection           *DetectionComponent           `protobuf:"bytes,16,opt,name=detection,proto3,oneof" json:"detection,omitempty"`
	Bearing             *BearingComponent             `protobuf:"bytes,17,opt,name=bearing,proto3,oneof" json:"bearing,omitempty"`
	LocationUncertainty *LocationUncertaintyComponent `protobuf:"bytes,20,opt,name=locationUncertainty,proto3,oneof" json:"locationUncertainty,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetController() *ControllerRef {
	if x != nil {
		return x.Controller
	}
	return nil
}

func (x *Entity) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *Entity) GetGeo() *GeoSpatialComponent {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Entity) GetSymbol() *SymbolComponent {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *Entity) GetCamera() *CameraComponent {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *Entity) GetDetection() *DetectionComponent {
	if x != nil {
		return x.Detection
	}
	return nil
}

func (x *Entity) GetBearing() *BearingComponent {
	if x != nil {
		return x.Bearing
	}
	return nil
}

func (x *Entity) GetLocationUncertainty() *LocationUncertaintyComponent {
	if x != nil {
		return x.LocationUncertainty
	}
	return nil
}

type ControllerRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerRef) Reset() {
	*x = ControllerRef{}
	mi := &file_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerRef) ProtoMessage() {}

func (x *ControllerRef) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerRef.ProtoReflect.Descriptor instead.
func (*ControllerRef) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControllerRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Lifetime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=until,proto3,oneof" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lifetime) Reset() {
	*x = Lifetime{}
	mi := &file_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifetime) ProtoMessage() {}

func (x *Lifetime) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifetime.ProtoReflect.Descriptor instead.
func (*Lifetime) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2}
}

func (x *Lifetime) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Lifetime) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type GeoSpatialComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSpatialComponent) Reset() {
	*x = GeoSpatialComponent{}
	mi := &file_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSpatialComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSpatialComponent) ProtoMessage() {}

func (x *GeoSpatialComponent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSpatialComponent.ProtoReflect.Descriptor instead.
func (*GeoSpatialComponent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3}
}

func (x *GeoSpatialComponent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoSpatialComponent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoSpatialComponent) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type SymbolComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilStd2525C   string                 `protobuf:"bytes,1,opt,name=milStd2525C,proto3" json:"milStd2525C,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolComponent) Reset() {
	*x = SymbolComponent{}
	mi := &file_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolComponent) ProtoMessage() {}

func (x *SymbolComponent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolComponent.ProtoReflect.Descriptor instead.
func (*SymbolComponent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4}
}

func (x *SymbolComponent) GetMilStd2525C() string {
	if x != nil {
		return x.MilStd2525C
	}
	return ""
}

type Camera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{5}
}

func (x *Camera) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Camera) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CameraComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cameras       []*Camera              `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraComponent) Reset() {
	*x = CameraComponent{}
	mi := &file_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraComponent) ProtoMessage() {}

func (x *CameraComponent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraComponent.ProtoReflect.Descriptor instead.
func (*CameraComponent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{6}
}

func (x *CameraComponent) GetCameras() []*Camera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type DetectionComponent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DetectorEntityID *string                `protobuf:"bytes,1,opt,name=detectorEntityID,proto3,oneof" json:"detectorEntityID,omitempty"`
	Classification   *string                `protobuf:"bytes,2,opt,name=classification,proto3,oneof" json:"classification,omitempty"`
	LastMeasured     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lastMeasured,proto3,oneof" json:"lastMeasured,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectionComponent) Reset() {
	*x = DetectionComponent{}
	mi := &file_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionComponent) ProtoMessage() {}

func (x *DetectionComponent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionComponent.ProtoReflect.Descriptor instead.
func (*DetectionComponent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{7}
}

func (x *DetectionComponent) GetDetectorEntityID() string {
	if x != nil && x.DetectorEntityID != nil {
		return *x.DetectorEntityID
	}
	return ""
}

func (x *DetectionComponent) GetClassification() string {
	if x != nil && x.Classification != nil {
		return *x.Classification
	}
	return ""
}

func (x *DetectionComponent) GetLastMeasured() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMeasured
	}
	return nil
}

type BearingComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Azimuth       *float64               `protobuf:"fixed64,1,opt,name=azimuth,proto3,oneof" json:"azimuth,omitempty"`
	Elevation     *float64               `protobuf:"fixed64,2,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BearingComponent) Reset() {
	*x = BearingComponent{}
	mi := &file_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearingComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearingComponent) ProtoMessage() {}

func (x *BearingComponent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearingComponent.ProtoReflect.Descriptor instead.
func (*BearingComponent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{8}
}

func (x *BearingComponent) GetAzimuth() float64 {
	if x != nil && x.Azimuth != nil {
		return *x.Azimuth
	}
	return 0
}

func (x *BearingComponent) GetElevation() float64 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

type CovarianceMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mxx           *float64               `protobuf:"fixed64,1,opt,name=mxx,proto3,oneof" json:"mxx,omitempty"`
	Mxy           *float64               `protobuf:"fixed64,2,opt,name=mxy,proto3,oneof" json:"mxy,omitempty"`
	Mxz           *float64               `protobuf:"fixed64,3,opt,name=mxz,proto3,oneof" json:"mxz,omitempty"`
	Myy           *float64               `protobuf:"fixed64,4,opt,name=myy,proto3,oneof" json:"myy,omitempty"`
	Myz           *float64               `protobuf:"fixed64,5,opt,name=myz,proto3,oneof" json:"myz,omitempty"`
	Mzz           *float64               `protobuf:"fixed64,6,opt,name=mzz,proto3,oneof" json:"mzz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CovarianceMatrix) Reset() {
	*x = CovarianceMatrix{}
	mi := &file_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CovarianceMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CovarianceMatrix) ProtoMessage() {}

func (x *CovarianceMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CovarianceMatrix.ProtoReflect.Descriptor instead.
func (*CovarianceMatrix) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{9}
}

func (x *CovarianceMatrix) GetMxx() float64 {
	if x != nil && x.Mxx != nil {
		return *x.Mxx
	}
	return 0
}

func (x *CovarianceMatrix) GetMxy() float64 {
	if x != nil && x.Mxy != nil {
		return *x.Mxy
	}
	return 0
}

func (x *CovarianceMatrix) GetMxz() float64 {
	if x != nil && x.Mxz != nil {
		return *x.Mxz
	}
	return 0
}

func (x *CovarianceMatrix) GetMyy() float64 {
	if x != nil && x.Myy != nil {
		return *x.Myy
	}
	return 0
}

func (x *CovarianceMatrix) GetMyz() float64 {
	if x != nil && x.Myz != nil {
		return *x.Myz
	}
	return 0
}

func (x *CovarianceMatrix) GetMzz() float64 {
	if x != nil && x.Mzz != nil {
		return *x.Mzz
	}
	return 0
}

type LocationUncertaintyComponent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PositionEnuCov *CovarianceMatrix      `protobuf:"bytes,1,opt,name=positionEnuCov,proto3,oneof" json:"positionEnuCov,omitempty"`
	VelocityEnuCov *CovarianceMatrix      `protobuf:"bytes,2,opt,name=velocityEnuCov,proto3,oneof" json:"velocityEnuCov,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationUncertaintyComponent) Reset() {
	*x = LocationUncertaintyComponent{}
	mi := &file_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUncertaintyComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUncertaintyComponent) ProtoMessage() {}

func (x *LocationUncertaintyComponent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUncertaintyComponent.ProtoReflect.Descriptor instead.
func (*LocationUncertaintyComponent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{10}
}

func (x *LocationUncertaintyComponent) GetPositionEnuCov() *CovarianceMatrix {
	if x != nil {
		return x.PositionEnuCov
	}
	return nil
}

func (x *LocationUncertaintyComponent) GetVelocityEnuCov() *CovarianceMatrix {
	if x != nil {
		return x.VelocityEnuCov
	}
	return nil
}

type Geometry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wkb           []byte                 `protobuf:"bytes,1,opt,name=wkb,proto3" json:"wkb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_world_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{11}
}

func (x *Geometry) GetWkb() []byte {
	if x != nil {
		return x.Wkb
	}
	return nil
}

type ListEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geo           *Geometry              `protobuf:"bytes,2,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesRequest) Reset() {
	*x = ListEntitiesRequest{}
	mi := &file_world_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesRequest) ProtoMessage() {}

func (x *ListEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ListEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{12}
}

func (x *ListEntitiesRequest) GetGeo() *Geometry {
	if x != nil {
		return x.Geo
	}
	return nil
}

type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_world_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{13}
}

func (x *ListEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type EntityChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*Entity              `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityChangeRequest) Reset() {
	*x = EntityChangeRequest{}
	mi := &file_world_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityChangeRequest) ProtoMessage() {}

func (x *EntityChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityChangeRequest.ProtoReflect.Descriptor instead.
func (*EntityChangeRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{14}
}

func (x *EntityChangeRequest) GetChanges() []*Entity {
	if x != nil {
		return x.Changes
	}
	return nil
}

type EntityChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Debug         string                 `protobuf:"bytes,2,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityChangeResponse) Reset() {
	*x = EntityChangeResponse{}
	mi := &file_world_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityChangeResponse) ProtoMessage() {}

func (x *EntityChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityChangeResponse.ProtoReflect.Descriptor instead.
func (*EntityChangeResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{15}
}

func (x *EntityChangeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EntityChangeResponse) GetDebug() string {
	if x != nil {
		return x.Debug
	}
	return ""
}

type EntityChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	T             EntityChange           `protobuf:"varint,2,opt,name=t,proto3,enum=world.EntityChange" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityChangeEvent) Reset() {
	*x = EntityChangeEvent{}
	mi := &file_world_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityChangeEvent) ProtoMessage() {}

func (x *EntityChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityChangeEvent.ProtoReflect.Descriptor instead.
func (*EntityChangeEvent) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{16}
}

func (x *EntityChangeEvent) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityChangeEvent) GetT() EntityChange {
	if x != nil {
		return x.T
	}
	return EntityChange_Invalid
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_world_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{17}
}

func (x *GetEntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_world_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{18}
}

func (x *GetEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type ObserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverRequest) Reset() {
	*x = ObserverRequest{}
	mi := &file_world_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverRequest) ProtoMessage() {}

func (x *ObserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverRequest.ProtoReflect.Descriptor instead.
func (*ObserverRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{19}
}

type ObserverState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geo           *Geometry              `protobuf:"bytes,1,opt,name=geo,proto3" json:"geo,omitempty"`
	ViewHistory   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=viewHistory,proto3,oneof" json:"viewHistory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverState) Reset() {
	*x = ObserverState{}
	mi := &file_world_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverState) ProtoMessage() {}

func (x *ObserverState) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverState.ProtoReflect.Descriptor instead.
func (*ObserverState) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{20}
}

func (x *ObserverState) GetGeo() *Geometry {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *ObserverState) GetViewHistory() *timestamppb.Timestamp {
	if x != nil {
		return x.ViewHistory
	}
	return nil
}

var File_world_proto protoreflect.FileDescriptor

const file_world_proto_rawDesc = "" +
	"\n" +
	"\vworld.proto\x12\x05world\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x04\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"controller\x18\x03 \x01(\v2\x14.world.ControllerRefH\x00R\n" +
	"controller\x88\x01\x01\x120\n" +
	"\blifetime\x18\x04 \x01(\v2\x0f.world.LifetimeH\x01R\blifetime\x88\x01\x01\x121\n" +
	"\x03geo\x18\v \x01(\v2\x1a.world.GeoSpatialComponentH\x02R\x03geo\x88\x01\x01\x123\n" +
	"\x06symbol\x18\f \x01(\v2\x16.world.SymbolComponentH\x03R\x06symbol\x88\x01\x01\x123\n" +
	"\x06camera\x18\x0f \x01(\v2\x16.world.CameraComponentH\x04R\x06camera\x88\x01\x01\x12<\n" +
	"\tdetection\x18\x10 \x01(\v2\x19.world.DetectionComponentH\x05R\tdetection\x88\x01\x01\x126\n" +
	"\abearing\x18\x11 \x01(\v2\x17.world.BearingComponentH\x06R\abearing\x88\x01\x01\x12Z\n" +
	"\x13locationUncertainty\x18\x14 \x01(\v2#.world.LocationUncertaintyComponentH\aR\x13locationUncertainty\x88\x01\x01B\r\n" +
	"\v_controllerB\v\n" +
	"\t_lifetimeB\x06\n" +
	"\x04_geoB\t\n" +
	"\a_symbolB\t\n" +
	"\a_cameraB\f\n" +
	"\n" +
	"_detectionB\n" +
	"\n" +
	"\b_bearingB\x16\n" +
	"\x14_locationUncertainty\"3\n" +
	"\rControllerRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x89\x01\n" +
	"\bLifetime\x123\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x125\n" +
	"\x05until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x05until\x88\x01\x01B\a\n" +
	"\x05_fromB\b\n" +
	"\x06_until\"k\n" +
	"\x13GeoSpatialComponent\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\"3\n" +
	"\x0fSymbolComponent\x12 \n" +
	"\vmilStd2525C\x18\x01 \x01(\tR\vmilStd2525C\"0\n" +
	"\x06Camera\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\":\n" +
	"\x0fCameraComponent\x12'\n" +
	"\acameras\x18\x01 \x03(\v2\r.world.CameraR\acameras\"\xf0\x01\n" +
	"\x12DetectionComponent\x12/\n" +
	"\x10detectorEntityID\x18\x01 \x01(\tH\x00R\x10detectorEntityID\x88\x01\x01\x12+\n" +
	"\x0eclassification\x18\x02 \x01(\tH\x01R\x0eclassification\x88\x01\x01\x12C\n" +
	"\flastMeasured\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\flastMeasured\x88\x01\x01B\x13\n" +
	"\x11_detectorEntityIDB\x11\n" +
	"\x0f_classificationB\x0f\n" +
	"\r_lastMeasured\"n\n" +
	"\x10BearingComponent\x12\x1d\n" +
	"\aazimuth\x18\x01 \x01(\x01H\x00R\aazimuth\x88\x01\x01\x12!\n" +
	"\televation\x18\x02 \x01(\x01H\x01R\televation\x88\x01\x01B\n" +
	"\n" +
	"\b_azimuthB\f\n" +
	"\n" +
	"_elevation\"\xcc\x01\n" +
	"\x10CovarianceMatrix\x12\x15\n" +
	"\x03mxx\x18\x01 \x01(\x01H\x00R\x03mxx\x88\x01\x01\x12\x15\n" +
	"\x03mxy\x18\x02 \x01(\x01H\x01R\x03mxy\x88\x01\x01\x12\x15\n" +
	"\x03mxz\x18\x03 \x01(\x01H\x02R\x03mxz\x88\x01\x01\x12\x15\n" +
	"\x03myy\x18\x04 \x01(\x01H\x03R\x03myy\x88\x01\x01\x12\x15\n" +
	"\x03myz\x18\x05 \x01(\x01H\x04R\x03myz\x88\x01\x01\x12\x15\n" +
	"\x03mzz\x18\x06 \x01(\x01H\x05R\x03mzz\x88\x01\x01B\x06\n" +
	"\x04_mxxB\x06\n" +
	"\x04_mxyB\x06\n" +
	"\x04_mxzB\x06\n" +
	"\x04_myyB\x06\n" +
	"\x04_myzB\x06\n" +
	"\x04_mzz\"\xd0\x01\n" +
	"\x1cLocationUncertaintyComponent\x12D\n" +
	"\x0epositionEnuCov\x18\x01 \x01(\v2\x17.world.CovarianceMatrixH\x00R\x0epositionEnuCov\x88\x01\x01\x12D\n" +
	"\x0evelocityEnuCov\x18\x02 \x01(\v2\x17.world.CovarianceMatrixH\x01R\x0evelocityEnuCov\x88\x01\x01B\x11\n" +
	"\x0f_positionEnuCovB\x11\n" +
	"\x0f_velocityEnuCov\"\x1c\n" +
	"\bGeometry\x12\x10\n" +
	"\x03wkb\x18\x01 \x01(\fR\x03wkb\"E\n" +
	"\x13ListEntitiesRequest\x12&\n" +
	"\x03geo\x18\x02 \x01(\v2\x0f.world.GeometryH\x00R\x03geo\x88\x01\x01B\x06\n" +
	"\x04_geo\"A\n" +
	"\x14ListEntitiesResponse\x12)\n" +
	"\bentities\x18\x01 \x03(\v2\r.world.EntityR\bentities\">\n" +
	"\x13EntityChangeRequest\x12'\n" +
	"\achanges\x18\x01 \x03(\v2\r.world.EntityR\achanges\"H\n" +
	"\x14EntityChangeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\tR\x05debug\"]\n" +
	"\x11EntityChangeEvent\x12%\n" +
	"\x06entity\x18\x01 \x01(\v2\r.world.EntityR\x06entity\x12!\n" +
	"\x01t\x18\x02 \x01(\x0e2\x13.world.EntityChangeR\x01t\"\"\n" +
	"\x10GetEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x11GetEntityResponse\x12%\n" +
	"\x06entity\x18\x01 \x01(\v2\r.world.EntityR\x06entity\"\x11\n" +
	"\x0fObserverRequest\"\x85\x01\n" +
	"\rObserverState\x12!\n" +
	"\x03geo\x18\x01 \x01(\v2\x0f.world.GeometryR\x03geo\x12A\n" +
	"\vviewHistory\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vviewHistory\x88\x01\x01B\x0e\n" +
	"\f_viewHistory*E\n" +
	"\fEntityChange\x12\v\n" +
	"\aInvalid\x10\x00\x12\v\n" +
	"\aUpdated\x10\x01\x12\v\n" +
	"\aExpired\x10\x02\x12\x0e\n" +
	"\n" +
	"Unobserved\x10\x032\xdc\x02\n" +
	"\fWorldService\x12G\n" +
	"\fListEntities\x12\x1a.world.ListEntitiesRequest\x1a\x1b.world.ListEntitiesResponse\x12>\n" +
	"\tGetEntity\x12\x17.world.GetEntityRequest\x1a\x18.world.GetEntityResponse\x12G\n" +
	"\rWatchEntities\x12\x1a.world.ListEntitiesRequest\x1a\x18.world.EntityChangeEvent0\x01\x12?\n" +
	"\x04Push\x12\x1a.world.EntityChangeRequest\x1a\x1b.world.EntityChangeResponse\x129\n" +
	"\aObserve\x12\x16.world.ObserverRequest\x1a\x14.world.ObserverState0\x01B Z\x1egithub.com/projectqai/proto/gob\x06proto3"

var (
	file_world_proto_rawDescOnce sync.Once
	file_world_proto_rawDescData []byte
)

func file_world_proto_rawDescGZIP() []byte {
	file_world_proto_rawDescOnce.Do(func() {
		file_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)))
	})
	return file_world_proto_rawDescData
}

var file_world_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_world_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_world_proto_goTypes = []any{
	(EntityChange)(0),                    // 0: world.EntityChange
	(*Entity)(nil),                       // 1: world.Entity
	(*ControllerRef)(nil),                // 2: world.ControllerRef
	(*Lifetime)(nil),                     // 3: world.Lifetime
	(*GeoSpatialComponent)(nil),          // 4: world.GeoSpatialComponent
	(*SymbolComponent)(nil),              // 5: world.SymbolComponent
	(*Camera)(nil),                       // 6: world.Camera
	(*CameraComponent)(nil),              // 7: world.CameraComponent
	(*DetectionComponent)(nil),           // 8: world.DetectionComponent
	(*BearingComponent)(nil),             // 9: world.BearingComponent
	(*CovarianceMatrix)(nil),             // 10: world.CovarianceMatrix
	(*LocationUncertaintyComponent)(nil), // 11: world.LocationUncertaintyComponent
	(*Geometry)(nil),                     // 12: world.Geometry
	(*ListEntitiesRequest)(nil),          // 13: world.ListEntitiesRequest
	(*ListEntitiesResponse)(nil),         // 14: world.ListEntitiesResponse
	(*EntityChangeRequest)(nil),          // 15: world.EntityChangeRequest
	(*EntityChangeResponse)(nil),         // 16: world.EntityChangeResponse
	(*EntityChangeEvent)(nil),            // 17: world.EntityChangeEvent
	(*GetEntityRequest)(nil),             // 18: world.GetEntityRequest
	(*GetEntityResponse)(nil),            // 19: world.GetEntityResponse
	(*ObserverRequest)(nil),              // 20: world.ObserverRequest
	(*ObserverState)(nil),                // 21: world.ObserverState
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
}
var file_world_proto_depIdxs = []int32{
	2,  // 0: world.Entity.controller:type_name -> world.ControllerRef
	3,  // 1: world.Entity.lifetime:type_name -> world.Lifetime
	4,  // 2: world.Entity.geo:type_name -> world.GeoSpatialComponent
	5,  // 3: world.Entity.symbol:type_name -> world.SymbolComponent
	7,  // 4: world.Entity.camera:type_name -> world.CameraComponent
	8,  // 5: world.Entity.detection:type_name -> world.DetectionComponent
	9,  // 6: world.Entity.bearing:type_name -> world.BearingComponent
	11, // 7: world.Entity.locationUncertainty:type_name -> world.LocationUncertaintyComponent
	22, // 8: world.Lifetime.from:type_name -> google.protobuf.Timestamp
	22, // 9: world.Lifetime.until:type_name -> google.protobuf.Timestamp
	6,  // 10: world.CameraComponent.cameras:type_name -> world.Camera
	22, // 11: world.DetectionComponent.lastMeasured:type_name -> google.protobuf.Timestamp
	10, // 12: world.LocationUncertaintyComponent.positionEnuCov:type_name -> world.CovarianceMatrix
	10, // 13: world.LocationUncertaintyComponent.velocityEnuCov:type_name -> world.CovarianceMatrix
	12, // 14: world.ListEntitiesRequest.geo:type_name -> world.Geometry
	1,  // 15: world.ListEntitiesResponse.entities:type_name -> world.Entity
	1,  // 16: world.EntityChangeRequest.changes:type_name -> world.Entity
	1,  // 17: world.EntityChangeEvent.entity:type_name -> world.Entity
	0,  // 18: world.EntityChangeEvent.t:type_name -> world.EntityChange
	1,  // 19: world.GetEntityResponse.entity:type_name -> world.Entity
	12, // 20: world.ObserverState.geo:type_name -> world.Geometry
	22, // 21: world.ObserverState.viewHistory:type_name -> google.protobuf.Timestamp
	13, // 22: world.WorldService.ListEntities:input_type -> world.ListEntitiesRequest
	18, // 23: world.WorldService.GetEntity:input_type -> world.GetEntityRequest
	13, // 24: world.WorldService.WatchEntities:input_type -> world.ListEntitiesRequest
	15, // 25: world.WorldService.Push:input_type -> world.EntityChangeRequest
	20, // 26: world.WorldService.Observe:input_type -> world.ObserverRequest
	14, // 27: world.WorldService.ListEntities:output_type -> world.ListEntitiesResponse
	19, // 28: world.WorldService.GetEntity:output_type -> world.GetEntityResponse
	17, // 29: world.WorldService.WatchEntities:output_type -> world.EntityChangeEvent
	16, // 30: world.WorldService.Push:output_type -> world.EntityChangeResponse
	21, // 31: world.WorldService.Observe:output_type -> world.ObserverState
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	file_world_proto_msgTypes[0].OneofWrappers = []any{}
	file_world_proto_msgTypes[2].OneofWrappers = []any{}
	file_world_proto_msgTypes[7].OneofWrappers = []any{}
	file_world_proto_msgTypes[8].OneofWrappers = []any{}
	file_world_proto_msgTypes[9].OneofWrappers = []any{}
	file_world_proto_msgTypes[10].OneofWrappers = []any{}
	file_world_proto_msgTypes[12].OneofWrappers = []any{}
	file_world_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
		EnumInfos:         file_world_proto_enumTypes,
		MessageInfos:      file_world_proto_msgTypes,
	}.Build()
	File_world_proto = out.File
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
