// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: world.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorldService_ListEntities_FullMethodName  = "/world.WorldService/ListEntities"
	WorldService_GetEntity_FullMethodName     = "/world.WorldService/GetEntity"
	WorldService_WatchEntities_FullMethodName = "/world.WorldService/WatchEntities"
	WorldService_Push_FullMethodName          = "/world.WorldService/Push"
	WorldService_ExpireEntity_FullMethodName  = "/world.WorldService/ExpireEntity"
	WorldService_GetLocalNode_FullMethodName  = "/world.WorldService/GetLocalNode"
	WorldService_RunTask_FullMethodName       = "/world.WorldService/RunTask"
)

// WorldServiceClient is the client API for WorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// interact with the world model
type WorldServiceClient interface {
	// list entities present in the world once
	ListEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (*ListEntitiesResponse, error)
	// request every detail about one entity
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// continously monitor entities present in the world. this is used by downstream C2.
	WatchEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntityChangeEvent], error)
	// Create or update an entity. Used by capabilities.
	//
	// Push uses merge semantics: only components present (set) in the pushed entity
	// are updated. Components not included in the message are left unchanged.
	// Components cannot be removed once set.
	Push(ctx context.Context, in *EntityChangeRequest, opts ...grpc.CallOption) (*EntityChangeResponse, error)
	// expire an entity, setting its lifetime.until to now
	ExpireEntity(ctx context.Context, in *ExpireEntityRequest, opts ...grpc.CallOption) (*ExpireEntityResponse, error)
	// get information about the local node the client is connected to
	GetLocalNode(ctx context.Context, in *GetLocalNodeRequest, opts ...grpc.CallOption) (*GetLocalNodeResponse, error)
	// create an instance of a specific task entity
	RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskResponse, error)
}

type worldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldServiceClient(cc grpc.ClientConnInterface) WorldServiceClient {
	return &worldServiceClient{cc}
}

func (c *worldServiceClient) ListEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (*ListEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntitiesResponse)
	err := c.cc.Invoke(ctx, WorldService_ListEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, WorldService_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) WatchEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntityChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[0], WorldService_WatchEntities_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListEntitiesRequest, EntityChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_WatchEntitiesClient = grpc.ServerStreamingClient[EntityChangeEvent]

func (c *worldServiceClient) Push(ctx context.Context, in *EntityChangeRequest, opts ...grpc.CallOption) (*EntityChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityChangeResponse)
	err := c.cc.Invoke(ctx, WorldService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) ExpireEntity(ctx context.Context, in *ExpireEntityRequest, opts ...grpc.CallOption) (*ExpireEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireEntityResponse)
	err := c.cc.Invoke(ctx, WorldService_ExpireEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetLocalNode(ctx context.Context, in *GetLocalNodeRequest, opts ...grpc.CallOption) (*GetLocalNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalNodeResponse)
	err := c.cc.Invoke(ctx, WorldService_GetLocalNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunTaskResponse)
	err := c.cc.Invoke(ctx, WorldService_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldServiceServer is the server API for WorldService service.
// All implementations must embed UnimplementedWorldServiceServer
// for forward compatibility.
//
// interact with the world model
type WorldServiceServer interface {
	// list entities present in the world once
	ListEntities(context.Context, *ListEntitiesRequest) (*ListEntitiesResponse, error)
	// request every detail about one entity
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// continously monitor entities present in the world. this is used by downstream C2.
	WatchEntities(*ListEntitiesRequest, grpc.ServerStreamingServer[EntityChangeEvent]) error
	// Create or update an entity. Used by capabilities.
	//
	// Push uses merge semantics: only components present (set) in the pushed entity
	// are updated. Components not included in the message are left unchanged.
	// Components cannot be removed once set.
	Push(context.Context, *EntityChangeRequest) (*EntityChangeResponse, error)
	// expire an entity, setting its lifetime.until to now
	ExpireEntity(context.Context, *ExpireEntityRequest) (*ExpireEntityResponse, error)
	// get information about the local node the client is connected to
	GetLocalNode(context.Context, *GetLocalNodeRequest) (*GetLocalNodeResponse, error)
	// create an instance of a specific task entity
	RunTask(context.Context, *RunTaskRequest) (*RunTaskResponse, error)
	mustEmbedUnimplementedWorldServiceServer()
}

// UnimplementedWorldServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldServiceServer struct{}

func (UnimplementedWorldServiceServer) ListEntities(context.Context, *ListEntitiesRequest) (*ListEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntities not implemented")
}
func (UnimplementedWorldServiceServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedWorldServiceServer) WatchEntities(*ListEntitiesRequest, grpc.ServerStreamingServer[EntityChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchEntities not implemented")
}
func (UnimplementedWorldServiceServer) Push(context.Context, *EntityChangeRequest) (*EntityChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedWorldServiceServer) ExpireEntity(context.Context, *ExpireEntityRequest) (*ExpireEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireEntity not implemented")
}
func (UnimplementedWorldServiceServer) GetLocalNode(context.Context, *GetLocalNodeRequest) (*GetLocalNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalNode not implemented")
}
func (UnimplementedWorldServiceServer) RunTask(context.Context, *RunTaskRequest) (*RunTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedWorldServiceServer) mustEmbedUnimplementedWorldServiceServer() {}
func (UnimplementedWorldServiceServer) testEmbeddedByValue()                      {}

// UnsafeWorldServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldServiceServer will
// result in compilation errors.
type UnsafeWorldServiceServer interface {
	mustEmbedUnimplementedWorldServiceServer()
}

func RegisterWorldServiceServer(s grpc.ServiceRegistrar, srv WorldServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorldServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldService_ServiceDesc, srv)
}

func _WorldService_ListEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).ListEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_ListEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).ListEntities(ctx, req.(*ListEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_WatchEntities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEntitiesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorldServiceServer).WatchEntities(m, &grpc.GenericServerStream[ListEntitiesRequest, EntityChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_WatchEntitiesServer = grpc.ServerStreamingServer[EntityChangeEvent]

func _WorldService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).Push(ctx, req.(*EntityChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_ExpireEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).ExpireEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_ExpireEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).ExpireEntity(ctx, req.(*ExpireEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetLocalNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetLocalNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetLocalNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetLocalNode(ctx, req.(*GetLocalNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).RunTask(ctx, req.(*RunTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorldService_ServiceDesc is the grpc.ServiceDesc for WorldService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "world.WorldService",
	HandlerType: (*WorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEntities",
			Handler:    _WorldService_ListEntities_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _WorldService_GetEntity_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _WorldService_Push_Handler,
		},
		{
			MethodName: "ExpireEntity",
			Handler:    _WorldService_ExpireEntity_Handler,
		},
		{
			MethodName: "GetLocalNode",
			Handler:    _WorldService_GetLocalNode_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _WorldService_RunTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEntities",
			Handler:       _WorldService_WatchEntities_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "world.proto",
}
